// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/account.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Passwords            string   `protobuf:"bytes,3,opt,name=passwords,proto3" json:"passwords,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_01112809b536ae69, []int{0}
}

func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (m *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(m, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AccountInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountInfo) GetPasswords() string {
	if m != nil {
		return m.Passwords
	}
	return ""
}

func (m *AccountInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AccountInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *AccountInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AccountInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqSignIn struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Psw                  string   `protobuf:"bytes,2,opt,name=psw,proto3" json:"psw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignIn) Reset()         { *m = ReqSignIn{} }
func (m *ReqSignIn) String() string { return proto.CompactTextString(m) }
func (*ReqSignIn) ProtoMessage()    {}
func (*ReqSignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_01112809b536ae69, []int{1}
}

func (m *ReqSignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignIn.Unmarshal(m, b)
}
func (m *ReqSignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignIn.Marshal(b, m, deterministic)
}
func (m *ReqSignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignIn.Merge(m, src)
}
func (m *ReqSignIn) XXX_Size() int {
	return xxx_messageInfo_ReqSignIn.Size(m)
}
func (m *ReqSignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignIn.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignIn proto.InternalMessageInfo

func (m *ReqSignIn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqSignIn) GetPsw() string {
	if m != nil {
		return m.Psw
	}
	return ""
}

type ReqSetPasswords struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Psw                  string   `protobuf:"bytes,2,opt,name=psw,proto3" json:"psw,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSetPasswords) Reset()         { *m = ReqSetPasswords{} }
func (m *ReqSetPasswords) String() string { return proto.CompactTextString(m) }
func (*ReqSetPasswords) ProtoMessage()    {}
func (*ReqSetPasswords) Descriptor() ([]byte, []int) {
	return fileDescriptor_01112809b536ae69, []int{2}
}

func (m *ReqSetPasswords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSetPasswords.Unmarshal(m, b)
}
func (m *ReqSetPasswords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSetPasswords.Marshal(b, m, deterministic)
}
func (m *ReqSetPasswords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSetPasswords.Merge(m, src)
}
func (m *ReqSetPasswords) XXX_Size() int {
	return xxx_messageInfo_ReqSetPasswords.Size(m)
}
func (m *ReqSetPasswords) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSetPasswords.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSetPasswords proto.InternalMessageInfo

func (m *ReqSetPasswords) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqSetPasswords) GetPsw() string {
	if m != nil {
		return m.Psw
	}
	return ""
}

func (m *ReqSetPasswords) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyAccount struct {
	Info                 *AccountInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyAccount) Reset()         { *m = ReplyAccount{} }
func (m *ReplyAccount) String() string { return proto.CompactTextString(m) }
func (*ReplyAccount) ProtoMessage()    {}
func (*ReplyAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_01112809b536ae69, []int{3}
}

func (m *ReplyAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAccount.Unmarshal(m, b)
}
func (m *ReplyAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAccount.Marshal(b, m, deterministic)
}
func (m *ReplyAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAccount.Merge(m, src)
}
func (m *ReplyAccount) XXX_Size() int {
	return xxx_messageInfo_ReplyAccount.Size(m)
}
func (m *ReplyAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAccount.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAccount proto.InternalMessageInfo

func (m *ReplyAccount) GetInfo() *AccountInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyAccount) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountInfo)(nil), "omo.msp.user.AccountInfo")
	proto.RegisterType((*ReqSignIn)(nil), "omo.msp.user.ReqSignIn")
	proto.RegisterType((*ReqSetPasswords)(nil), "omo.msp.user.ReqSetPasswords")
	proto.RegisterType((*ReplyAccount)(nil), "omo.msp.user.ReplyAccount")
}

func init() {
	proto.RegisterFile("proto/user/account.proto", fileDescriptor_01112809b536ae69)
}

var fileDescriptor_01112809b536ae69 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x6e, 0xe2, 0x30,
	0x10, 0xc6, 0x09, 0x61, 0xc3, 0x32, 0x44, 0xbb, 0xc8, 0x17, 0xd2, 0xa8, 0x95, 0x50, 0x4e, 0x5c,
	0x1a, 0x04, 0xbd, 0xf6, 0x02, 0x97, 0x96, 0x4b, 0xff, 0x04, 0xf5, 0xd2, 0x5b, 0x9a, 0x98, 0x2a,
	0x52, 0x63, 0x9b, 0x38, 0x29, 0xea, 0xd3, 0xf4, 0x41, 0xfa, 0x72, 0x95, 0x27, 0x26, 0x84, 0x86,
	0x72, 0x9b, 0x99, 0x6f, 0xe6, 0xe7, 0xcf, 0x63, 0x83, 0x23, 0x32, 0x9e, 0xf3, 0x49, 0x21, 0x69,
	0x36, 0x09, 0xa3, 0x88, 0x17, 0x2c, 0xf7, 0xb1, 0x44, 0x6c, 0x9e, 0x72, 0x3f, 0x95, 0xc2, 0x57,
	0x9a, 0x3b, 0xac, 0xf5, 0x45, 0x3c, 0x4d, 0x39, 0x2b, 0xdb, 0xbc, 0x2f, 0x03, 0xfa, 0xf3, 0x72,
	0x70, 0xc9, 0xd6, 0x9c, 0x0c, 0xc0, 0x2c, 0x92, 0xd8, 0x31, 0x46, 0xc6, 0xb8, 0x17, 0xa8, 0x90,
	0x10, 0xe8, 0xb0, 0x30, 0xa5, 0x4e, 0x1b, 0x4b, 0x18, 0x93, 0x73, 0xe8, 0x89, 0x50, 0xca, 0x2d,
	0xcf, 0x62, 0xe9, 0x98, 0x28, 0xec, 0x0b, 0xc4, 0x81, 0x6e, 0x94, 0xd1, 0x30, 0xa7, 0xb1, 0xd3,
	0x19, 0x19, 0x63, 0x33, 0xd8, 0xa5, 0x4a, 0x29, 0x44, 0x8c, 0xca, 0x9f, 0x52, 0xd1, 0x69, 0x35,
	0xc3, 0x33, 0xc7, 0x42, 0xde, 0x2e, 0x25, 0x2e, 0xfc, 0xe5, 0x82, 0x66, 0x28, 0x75, 0x51, 0xaa,
	0x72, 0x6f, 0x0a, 0xbd, 0x80, 0x6e, 0x56, 0xc9, 0x2b, 0x5b, 0xb2, 0xca, 0xa8, 0x51, 0x33, 0x3a,
	0x00, 0x53, 0xc8, 0xad, 0xf6, 0xae, 0x42, 0xef, 0x11, 0xfe, 0xab, 0x11, 0x9a, 0x3f, 0x54, 0x7e,
	0x9b, 0x77, 0x6e, 0x8c, 0x1d, 0xb8, 0x30, 0x7f, 0xb8, 0x10, 0x60, 0x07, 0x54, 0xbc, 0x7d, 0xe8,
	0x3d, 0x92, 0x4b, 0xe8, 0x24, 0x6c, 0xcd, 0x11, 0xd8, 0x9f, 0x9d, 0xf9, 0xf5, 0x97, 0xf0, 0x6b,
	0xcb, 0x0e, 0xb0, 0x8d, 0x4c, 0xc1, 0x92, 0x79, 0x98, 0x17, 0x12, 0xcf, 0x6b, 0x0c, 0x20, 0x7a,
	0x85, 0x0d, 0x81, 0x6e, 0x9c, 0x7d, 0xb6, 0xe1, 0x9f, 0x06, 0xad, 0x68, 0xf6, 0x9e, 0x44, 0x94,
	0xcc, 0xc1, 0xba, 0xa1, 0xf9, 0x3d, 0xa3, 0xa4, 0x31, 0xbf, 0x29, 0xa8, 0xc4, 0x03, 0x5d, 0xf7,
	0x08, 0x5a, 0x73, 0xbc, 0x16, 0xb9, 0x06, 0x4b, 0xaf, 0x72, 0xd8, 0x40, 0x94, 0x82, 0x3b, 0x3c,
	0x02, 0x50, 0x64, 0xaf, 0x45, 0x6e, 0xc1, 0x3e, 0xd8, 0xea, 0x45, 0x93, 0x51, 0x93, 0x4f, 0x91,
	0x16, 0x00, 0x4f, 0xf8, 0x2d, 0xee, 0xd4, 0x13, 0x9e, 0xb8, 0xce, 0xef, 0x8c, 0x85, 0xfd, 0x0c,
	0xfb, 0x2f, 0xff, 0x62, 0x61, 0x7c, 0xf5, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x89, 0xd0, 0xc4,
	0x2f, 0x03, 0x00, 0x00,
}
