// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/behaviour.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BehaviourInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Created              uint64   `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Creator              string   `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Type                 uint32   `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
	Action               uint32   `protobuf:"varint,8,opt,name=action,proto3" json:"action,omitempty"`
	Updated              uint64   `protobuf:"varint,9,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BehaviourInfo) Reset()         { *m = BehaviourInfo{} }
func (m *BehaviourInfo) String() string { return proto.CompactTextString(m) }
func (*BehaviourInfo) ProtoMessage()    {}
func (*BehaviourInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b383772d9e07c3, []int{0}
}

func (m *BehaviourInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BehaviourInfo.Unmarshal(m, b)
}
func (m *BehaviourInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BehaviourInfo.Marshal(b, m, deterministic)
}
func (m *BehaviourInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BehaviourInfo.Merge(m, src)
}
func (m *BehaviourInfo) XXX_Size() int {
	return xxx_messageInfo_BehaviourInfo.Size(m)
}
func (m *BehaviourInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BehaviourInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BehaviourInfo proto.InternalMessageInfo

func (m *BehaviourInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *BehaviourInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *BehaviourInfo) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *BehaviourInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *BehaviourInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BehaviourInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *BehaviourInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *BehaviourInfo) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *BehaviourInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type ReqBehaviourAdd struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Action               uint32   `protobuf:"varint,5,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBehaviourAdd) Reset()         { *m = ReqBehaviourAdd{} }
func (m *ReqBehaviourAdd) String() string { return proto.CompactTextString(m) }
func (*ReqBehaviourAdd) ProtoMessage()    {}
func (*ReqBehaviourAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b383772d9e07c3, []int{1}
}

func (m *ReqBehaviourAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBehaviourAdd.Unmarshal(m, b)
}
func (m *ReqBehaviourAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBehaviourAdd.Marshal(b, m, deterministic)
}
func (m *ReqBehaviourAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBehaviourAdd.Merge(m, src)
}
func (m *ReqBehaviourAdd) XXX_Size() int {
	return xxx_messageInfo_ReqBehaviourAdd.Size(m)
}
func (m *ReqBehaviourAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBehaviourAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBehaviourAdd proto.InternalMessageInfo

func (m *ReqBehaviourAdd) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReqBehaviourAdd) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ReqBehaviourAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqBehaviourAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqBehaviourAdd) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

type ReqBehaviourCheck struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Action               uint32   `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
	Type                 uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBehaviourCheck) Reset()         { *m = ReqBehaviourCheck{} }
func (m *ReqBehaviourCheck) String() string { return proto.CompactTextString(m) }
func (*ReqBehaviourCheck) ProtoMessage()    {}
func (*ReqBehaviourCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b383772d9e07c3, []int{2}
}

func (m *ReqBehaviourCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBehaviourCheck.Unmarshal(m, b)
}
func (m *ReqBehaviourCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBehaviourCheck.Marshal(b, m, deterministic)
}
func (m *ReqBehaviourCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBehaviourCheck.Merge(m, src)
}
func (m *ReqBehaviourCheck) XXX_Size() int {
	return xxx_messageInfo_ReqBehaviourCheck.Size(m)
}
func (m *ReqBehaviourCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBehaviourCheck.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBehaviourCheck proto.InternalMessageInfo

func (m *ReqBehaviourCheck) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReqBehaviourCheck) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ReqBehaviourCheck) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *ReqBehaviourCheck) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ReqBehaviourUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Action               uint32   `protobuf:"varint,4,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBehaviourUpdate) Reset()         { *m = ReqBehaviourUpdate{} }
func (m *ReqBehaviourUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqBehaviourUpdate) ProtoMessage()    {}
func (*ReqBehaviourUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b383772d9e07c3, []int{3}
}

func (m *ReqBehaviourUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBehaviourUpdate.Unmarshal(m, b)
}
func (m *ReqBehaviourUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBehaviourUpdate.Marshal(b, m, deterministic)
}
func (m *ReqBehaviourUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBehaviourUpdate.Merge(m, src)
}
func (m *ReqBehaviourUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqBehaviourUpdate.Size(m)
}
func (m *ReqBehaviourUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBehaviourUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBehaviourUpdate proto.InternalMessageInfo

func (m *ReqBehaviourUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqBehaviourUpdate) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReqBehaviourUpdate) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ReqBehaviourUpdate) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

type ReqBehaviourList struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBehaviourList) Reset()         { *m = ReqBehaviourList{} }
func (m *ReqBehaviourList) String() string { return proto.CompactTextString(m) }
func (*ReqBehaviourList) ProtoMessage()    {}
func (*ReqBehaviourList) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b383772d9e07c3, []int{4}
}

func (m *ReqBehaviourList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBehaviourList.Unmarshal(m, b)
}
func (m *ReqBehaviourList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBehaviourList.Marshal(b, m, deterministic)
}
func (m *ReqBehaviourList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBehaviourList.Merge(m, src)
}
func (m *ReqBehaviourList) XXX_Size() int {
	return xxx_messageInfo_ReqBehaviourList.Size(m)
}
func (m *ReqBehaviourList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBehaviourList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBehaviourList proto.InternalMessageInfo

func (m *ReqBehaviourList) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReqBehaviourList) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ReqBehaviourList) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ReplyBehaviourCheck struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Had                  bool         `protobuf:"varint,2,opt,name=had,proto3" json:"had,omitempty"`
	Count                uint32       `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyBehaviourCheck) Reset()         { *m = ReplyBehaviourCheck{} }
func (m *ReplyBehaviourCheck) String() string { return proto.CompactTextString(m) }
func (*ReplyBehaviourCheck) ProtoMessage()    {}
func (*ReplyBehaviourCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b383772d9e07c3, []int{5}
}

func (m *ReplyBehaviourCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyBehaviourCheck.Unmarshal(m, b)
}
func (m *ReplyBehaviourCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyBehaviourCheck.Marshal(b, m, deterministic)
}
func (m *ReplyBehaviourCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyBehaviourCheck.Merge(m, src)
}
func (m *ReplyBehaviourCheck) XXX_Size() int {
	return xxx_messageInfo_ReplyBehaviourCheck.Size(m)
}
func (m *ReplyBehaviourCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyBehaviourCheck.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyBehaviourCheck proto.InternalMessageInfo

func (m *ReplyBehaviourCheck) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyBehaviourCheck) GetHad() bool {
	if m != nil {
		return m.Had
	}
	return false
}

func (m *ReplyBehaviourCheck) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ReplyBehaviourList struct {
	Status               *ReplyStatus     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*BehaviourInfo `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReplyBehaviourList) Reset()         { *m = ReplyBehaviourList{} }
func (m *ReplyBehaviourList) String() string { return proto.CompactTextString(m) }
func (*ReplyBehaviourList) ProtoMessage()    {}
func (*ReplyBehaviourList) Descriptor() ([]byte, []int) {
	return fileDescriptor_86b383772d9e07c3, []int{6}
}

func (m *ReplyBehaviourList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyBehaviourList.Unmarshal(m, b)
}
func (m *ReplyBehaviourList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyBehaviourList.Marshal(b, m, deterministic)
}
func (m *ReplyBehaviourList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyBehaviourList.Merge(m, src)
}
func (m *ReplyBehaviourList) XXX_Size() int {
	return xxx_messageInfo_ReplyBehaviourList.Size(m)
}
func (m *ReplyBehaviourList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyBehaviourList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyBehaviourList proto.InternalMessageInfo

func (m *ReplyBehaviourList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyBehaviourList) GetList() []*BehaviourInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*BehaviourInfo)(nil), "omo.msp.user.BehaviourInfo")
	proto.RegisterType((*ReqBehaviourAdd)(nil), "omo.msp.user.ReqBehaviourAdd")
	proto.RegisterType((*ReqBehaviourCheck)(nil), "omo.msp.user.ReqBehaviourCheck")
	proto.RegisterType((*ReqBehaviourUpdate)(nil), "omo.msp.user.ReqBehaviourUpdate")
	proto.RegisterType((*ReqBehaviourList)(nil), "omo.msp.user.ReqBehaviourList")
	proto.RegisterType((*ReplyBehaviourCheck)(nil), "omo.msp.user.ReplyBehaviourCheck")
	proto.RegisterType((*ReplyBehaviourList)(nil), "omo.msp.user.ReplyBehaviourList")
}

func init() {
	proto.RegisterFile("proto/user/behaviour.proto", fileDescriptor_86b383772d9e07c3)
}

var fileDescriptor_86b383772d9e07c3 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x72, 0x93, 0x50,
	0x10, 0x0e, 0x0d, 0x21, 0xc9, 0x26, 0x1d, 0xe3, 0xd1, 0xb1, 0x47, 0xea, 0x0f, 0x72, 0x95, 0xab,
	0x64, 0x8c, 0x4f, 0xd0, 0x74, 0xc6, 0xb4, 0x33, 0xfe, 0x74, 0xe8, 0x78, 0xe3, 0x1d, 0x85, 0xb5,
	0xc1, 0x06, 0x0e, 0x85, 0x43, 0xc7, 0x3c, 0x80, 0x6f, 0xe3, 0x1b, 0xf9, 0x32, 0xce, 0x59, 0x20,
	0x40, 0x4d, 0x3a, 0x6a, 0xbd, 0xdb, 0x5d, 0xbe, 0xfd, 0xbe, 0x6f, 0x77, 0x4f, 0x02, 0x66, 0x9c,
	0x08, 0x29, 0xa6, 0x59, 0x8a, 0xc9, 0xf4, 0x02, 0x97, 0xee, 0x4d, 0x20, 0xb2, 0x64, 0x42, 0x45,
	0x36, 0x14, 0xa1, 0x98, 0x84, 0x69, 0x3c, 0x51, 0x5f, 0xcd, 0x83, 0x1a, 0xd2, 0x13, 0x61, 0x28,
	0xa2, 0x1c, 0x66, 0xff, 0xd4, 0x60, 0x7f, 0x5e, 0xb6, 0x9e, 0x46, 0x5f, 0x04, 0x1b, 0x41, 0x3b,
	0x0b, 0x7c, 0xae, 0x59, 0xda, 0xb8, 0xef, 0xa8, 0x90, 0x31, 0xd0, 0x55, 0x23, 0xdf, 0xa3, 0x12,
	0xc5, 0xec, 0x09, 0x18, 0xd2, 0x4d, 0x2e, 0x51, 0xf2, 0x36, 0x55, 0x8b, 0x8c, 0x71, 0xe8, 0x7a,
	0x09, 0xba, 0x12, 0x7d, 0xae, 0x5b, 0xda, 0x58, 0x77, 0xca, 0x54, 0xb1, 0x44, 0x6e, 0x88, 0xbc,
	0x93, 0xb3, 0xa8, 0x78, 0x83, 0x16, 0x09, 0x37, 0xa8, 0x5c, 0xa6, 0x0a, 0x2d, 0xd7, 0x31, 0xf2,
	0xae, 0xa5, 0x8d, 0xf7, 0x1d, 0x8a, 0x95, 0xa6, 0xeb, 0xc9, 0x40, 0x44, 0xbc, 0x47, 0xd5, 0x22,
	0x53, 0x2c, 0x59, 0xec, 0x93, 0x66, 0x3f, 0xd7, 0x2c, 0x52, 0xfb, 0xbb, 0x06, 0x0f, 0x1c, 0xbc,
	0xde, 0x0c, 0x78, 0xe4, 0x57, 0xd3, 0x68, 0x5b, 0xa7, 0xd9, 0x6b, 0x4c, 0x53, 0xba, 0x68, 0xd7,
	0x5c, 0x98, 0xd0, 0x13, 0x31, 0x26, 0x64, 0x5a, 0x27, 0xf4, 0x26, 0xaf, 0x39, 0xec, 0xd4, 0x1d,
	0xda, 0x57, 0xf0, 0xb0, 0x6e, 0xe3, 0x78, 0x89, 0xde, 0xd5, 0x5f, 0x19, 0xa9, 0x88, 0xdb, 0x8d,
	0xd1, 0x4b, 0x83, 0x7a, 0x65, 0xd0, 0xfe, 0x0a, 0xac, 0x2e, 0xf6, 0x89, 0x76, 0x71, 0xcf, 0xb3,
	0x56, 0xfa, 0x7a, 0x63, 0x30, 0x07, 0x46, 0x75, 0xad, 0x77, 0x41, 0x2a, 0xef, 0xbb, 0x60, 0x3b,
	0x86, 0x47, 0x0e, 0xc6, 0xab, 0xf5, 0xad, 0x75, 0xbd, 0x06, 0x23, 0x95, 0xae, 0xcc, 0x52, 0x22,
	0x1e, 0xcc, 0x9e, 0x4e, 0xea, 0x2f, 0x7c, 0x42, 0x2d, 0xe7, 0x04, 0x70, 0x0a, 0xa0, 0x9a, 0x79,
	0xe9, 0xfa, 0x24, 0xd9, 0x73, 0x54, 0xc8, 0x1e, 0x43, 0xc7, 0x13, 0x59, 0x24, 0x0b, 0xc1, 0x3c,
	0xb1, 0xbf, 0xa9, 0x8d, 0xd5, 0x15, 0x69, 0x8e, 0x7f, 0x10, 0x9c, 0x82, 0xbe, 0x0a, 0x52, 0xc9,
	0x07, 0x56, 0x7b, 0x3c, 0x98, 0x1d, 0x36, 0x1b, 0x1a, 0x3f, 0x33, 0x87, 0x80, 0xb3, 0x1f, 0x3a,
	0x8c, 0x36, 0xf5, 0x73, 0x4c, 0x6e, 0x02, 0x0f, 0xd9, 0x1c, 0x8c, 0x23, 0xdf, 0xff, 0x18, 0x21,
	0x7b, 0x7e, 0x5b, 0xb2, 0xf1, 0x94, 0xcd, 0x83, 0x2d, 0x8e, 0x14, 0xb9, 0xdd, 0x62, 0x1f, 0xc0,
	0x38, 0x71, 0x89, 0xe3, 0xe5, 0x6e, 0x0e, 0x5a, 0xac, 0xf9, 0x6a, 0x0b, 0x4b, 0x13, 0x62, 0xb7,
	0xd8, 0x09, 0xf4, 0xf3, 0x87, 0xa4, 0x28, 0xad, 0xdd, 0x94, 0x39, 0xe8, 0x2e, 0x67, 0x67, 0xd0,
	0x5b, 0xa0, 0x3c, 0x56, 0x8b, 0xff, 0x4f, 0xde, 0xde, 0x43, 0x77, 0x81, 0x92, 0x6e, 0xf6, 0x62,
	0x37, 0xa1, 0xfa, 0x6e, 0x5a, 0x77, 0xf1, 0x29, 0x84, 0xdd, 0x62, 0xa7, 0x30, 0x5c, 0xa0, 0x54,
	0x97, 0x0d, 0x52, 0x19, 0x78, 0xec, 0xb7, 0xbb, 0x5f, 0x67, 0x98, 0xca, 0x33, 0xf7, 0x12, 0xcd,
	0x67, 0x3b, 0x9e, 0x04, 0x35, 0xd2, 0x15, 0x06, 0x0b, 0x94, 0xf3, 0xf5, 0xdb, 0x60, 0x25, 0x31,
	0x61, 0x87, 0x5b, 0x99, 0xf2, 0x8f, 0x7f, 0x62, 0x6d, 0x3e, 0xfc, 0x0c, 0xd5, 0x1f, 0xf9, 0x85,
	0x41, 0xf1, 0x9b, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x80, 0x55, 0x00, 0xb3, 0x07, 0x06, 0x00,
	0x00,
}
