// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/message.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MessageService service

type MessageService interface {
	AddOne(ctx context.Context, in *ReqMessageAdd, opts ...client.CallOption) (*ReplyInfo, error)
	GetStatistic(ctx context.Context, in *RequestPage, opts ...client.CallOption) (*ReplyStatistic, error)
	GetList(ctx context.Context, in *RequestPage, opts ...client.CallOption) (*ReplyMessageList, error)
	UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, opts ...client.CallOption) (*ReplyInfo, error)
}

type messageService struct {
	c    client.Client
	name string
}

func NewMessageService(name string, c client.Client) MessageService {
	return &messageService{
		c:    c,
		name: name,
	}
}

func (c *messageService) AddOne(ctx context.Context, in *ReqMessageAdd, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "MessageService.AddOne", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageService) GetStatistic(ctx context.Context, in *RequestPage, opts ...client.CallOption) (*ReplyStatistic, error) {
	req := c.c.NewRequest(c.name, "MessageService.GetStatistic", in)
	out := new(ReplyStatistic)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageService) GetList(ctx context.Context, in *RequestPage, opts ...client.CallOption) (*ReplyMessageList, error) {
	req := c.c.NewRequest(c.name, "MessageService.GetList", in)
	out := new(ReplyMessageList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageService) UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "MessageService.UpdateByFilter", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MessageService service

type MessageServiceHandler interface {
	AddOne(context.Context, *ReqMessageAdd, *ReplyInfo) error
	GetStatistic(context.Context, *RequestPage, *ReplyStatistic) error
	GetList(context.Context, *RequestPage, *ReplyMessageList) error
	UpdateByFilter(context.Context, *ReqUpdateFilter, *ReplyInfo) error
}

func RegisterMessageServiceHandler(s server.Server, hdlr MessageServiceHandler, opts ...server.HandlerOption) error {
	type messageService interface {
		AddOne(ctx context.Context, in *ReqMessageAdd, out *ReplyInfo) error
		GetStatistic(ctx context.Context, in *RequestPage, out *ReplyStatistic) error
		GetList(ctx context.Context, in *RequestPage, out *ReplyMessageList) error
		UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, out *ReplyInfo) error
	}
	type MessageService struct {
		messageService
	}
	h := &messageServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MessageService{h}, opts...))
}

type messageServiceHandler struct {
	MessageServiceHandler
}

func (h *messageServiceHandler) AddOne(ctx context.Context, in *ReqMessageAdd, out *ReplyInfo) error {
	return h.MessageServiceHandler.AddOne(ctx, in, out)
}

func (h *messageServiceHandler) GetStatistic(ctx context.Context, in *RequestPage, out *ReplyStatistic) error {
	return h.MessageServiceHandler.GetStatistic(ctx, in, out)
}

func (h *messageServiceHandler) GetList(ctx context.Context, in *RequestPage, out *ReplyMessageList) error {
	return h.MessageServiceHandler.GetList(ctx, in, out)
}

func (h *messageServiceHandler) UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, out *ReplyInfo) error {
	return h.MessageServiceHandler.UpdateByFilter(ctx, in, out)
}
