// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/registers.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OCRResult struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Entity               string   `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OCRResult) Reset()         { *m = OCRResult{} }
func (m *OCRResult) String() string { return proto.CompactTextString(m) }
func (*OCRResult) ProtoMessage()    {}
func (*OCRResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8420811b64eed10, []int{0}
}

func (m *OCRResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OCRResult.Unmarshal(m, b)
}
func (m *OCRResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OCRResult.Marshal(b, m, deterministic)
}
func (m *OCRResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OCRResult.Merge(m, src)
}
func (m *OCRResult) XXX_Size() int {
	return xxx_messageInfo_OCRResult.Size(m)
}
func (m *OCRResult) XXX_DiscardUnknown() {
	xxx_messageInfo_OCRResult.DiscardUnknown(m)
}

var xxx_messageInfo_OCRResult proto.InternalMessageInfo

func (m *OCRResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OCRResult) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *OCRResult) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

type RegistersInfo struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64       `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 uint32       `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Created              int64        `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64        `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string       `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string       `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string       `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string       `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string       `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	Activity             string       `protobuf:"bytes,11,opt,name=activity,proto3" json:"activity,omitempty"`
	Quote                string       `protobuf:"bytes,12,opt,name=quote,proto3" json:"quote,omitempty"`
	Asset                string       `protobuf:"bytes,13,opt,name=asset,proto3" json:"asset,omitempty"`
	Results              []*OCRResult `protobuf:"bytes,21,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegistersInfo) Reset()         { *m = RegistersInfo{} }
func (m *RegistersInfo) String() string { return proto.CompactTextString(m) }
func (*RegistersInfo) ProtoMessage()    {}
func (*RegistersInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8420811b64eed10, []int{1}
}

func (m *RegistersInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistersInfo.Unmarshal(m, b)
}
func (m *RegistersInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistersInfo.Marshal(b, m, deterministic)
}
func (m *RegistersInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistersInfo.Merge(m, src)
}
func (m *RegistersInfo) XXX_Size() int {
	return xxx_messageInfo_RegistersInfo.Size(m)
}
func (m *RegistersInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistersInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RegistersInfo proto.InternalMessageInfo

func (m *RegistersInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RegistersInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegistersInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RegistersInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *RegistersInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *RegistersInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *RegistersInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RegistersInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegistersInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *RegistersInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *RegistersInfo) GetActivity() string {
	if m != nil {
		return m.Activity
	}
	return ""
}

func (m *RegistersInfo) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *RegistersInfo) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *RegistersInfo) GetResults() []*OCRResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type ReqRegistersAdd struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Quote                string   `protobuf:"bytes,6,opt,name=quote,proto3" json:"quote,omitempty"`
	Color                string   `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	Ignore               uint32   `protobuf:"varint,8,opt,name=ignore,proto3" json:"ignore,omitempty"`
	Type                 uint32   `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	Targets              []string `protobuf:"bytes,15,rep,name=targets,proto3" json:"targets,omitempty"`
	Weekdays             []uint32 `protobuf:"varint,16,rep,packed,name=weekdays,proto3" json:"weekdays,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRegistersAdd) Reset()         { *m = ReqRegistersAdd{} }
func (m *ReqRegistersAdd) String() string { return proto.CompactTextString(m) }
func (*ReqRegistersAdd) ProtoMessage()    {}
func (*ReqRegistersAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8420811b64eed10, []int{2}
}

func (m *ReqRegistersAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRegistersAdd.Unmarshal(m, b)
}
func (m *ReqRegistersAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRegistersAdd.Marshal(b, m, deterministic)
}
func (m *ReqRegistersAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRegistersAdd.Merge(m, src)
}
func (m *ReqRegistersAdd) XXX_Size() int {
	return xxx_messageInfo_ReqRegistersAdd.Size(m)
}
func (m *ReqRegistersAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRegistersAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRegistersAdd proto.InternalMessageInfo

func (m *ReqRegistersAdd) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqRegistersAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqRegistersAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqRegistersAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqRegistersAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqRegistersAdd) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *ReqRegistersAdd) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *ReqRegistersAdd) GetIgnore() uint32 {
	if m != nil {
		return m.Ignore
	}
	return 0
}

func (m *ReqRegistersAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqRegistersAdd) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *ReqRegistersAdd) GetWeekdays() []uint32 {
	if m != nil {
		return m.Weekdays
	}
	return nil
}

type ReplyRegistersInfo struct {
	Status               *ReplyStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *RegistersInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyRegistersInfo) Reset()         { *m = ReplyRegistersInfo{} }
func (m *ReplyRegistersInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyRegistersInfo) ProtoMessage()    {}
func (*ReplyRegistersInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8420811b64eed10, []int{3}
}

func (m *ReplyRegistersInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRegistersInfo.Unmarshal(m, b)
}
func (m *ReplyRegistersInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRegistersInfo.Marshal(b, m, deterministic)
}
func (m *ReplyRegistersInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRegistersInfo.Merge(m, src)
}
func (m *ReplyRegistersInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyRegistersInfo.Size(m)
}
func (m *ReplyRegistersInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRegistersInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRegistersInfo proto.InternalMessageInfo

func (m *ReplyRegistersInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyRegistersInfo) GetInfo() *RegistersInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyRegistersList struct {
	Status               *ReplyStatus     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32           `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32           `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32           `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*RegistersInfo `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReplyRegistersList) Reset()         { *m = ReplyRegistersList{} }
func (m *ReplyRegistersList) String() string { return proto.CompactTextString(m) }
func (*ReplyRegistersList) ProtoMessage()    {}
func (*ReplyRegistersList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8420811b64eed10, []int{4}
}

func (m *ReplyRegistersList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRegistersList.Unmarshal(m, b)
}
func (m *ReplyRegistersList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRegistersList.Marshal(b, m, deterministic)
}
func (m *ReplyRegistersList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRegistersList.Merge(m, src)
}
func (m *ReplyRegistersList) XXX_Size() int {
	return xxx_messageInfo_ReplyRegistersList.Size(m)
}
func (m *ReplyRegistersList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRegistersList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRegistersList proto.InternalMessageInfo

func (m *ReplyRegistersList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyRegistersList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyRegistersList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyRegistersList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyRegistersList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyRegistersList) GetList() []*RegistersInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*OCRResult)(nil), "omo.msp.user.OCRResult")
	proto.RegisterType((*RegistersInfo)(nil), "omo.msp.user.RegistersInfo")
	proto.RegisterType((*ReqRegistersAdd)(nil), "omo.msp.user.ReqRegistersAdd")
	proto.RegisterType((*ReplyRegistersInfo)(nil), "omo.msp.user.ReplyRegistersInfo")
	proto.RegisterType((*ReplyRegistersList)(nil), "omo.msp.user.ReplyRegistersList")
}

func init() {
	proto.RegisterFile("proto/user/registers.proto", fileDescriptor_c8420811b64eed10)
}

var fileDescriptor_c8420811b64eed10 = []byte{
	// 647 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x4e, 0xdb, 0x30,
	0x14, 0xa6, 0x4d, 0x1b, 0xe8, 0x69, 0x03, 0xc8, 0x62, 0x90, 0x95, 0x4d, 0xaa, 0x72, 0xd5, 0xab,
	0x22, 0xba, 0x27, 0x80, 0x49, 0xab, 0x36, 0xb6, 0x21, 0x19, 0xed, 0x66, 0x77, 0xa1, 0x39, 0x74,
	0x16, 0x4d, 0x1c, 0x6c, 0xa7, 0xac, 0x4f, 0xb1, 0x57, 0xdb, 0xc5, 0x1e, 0x63, 0x0f, 0x31, 0xf9,
	0x38, 0xcd, 0xda, 0x52, 0x60, 0xda, 0x9d, 0xbf, 0xf3, 0xf3, 0x1d, 0x7f, 0xdf, 0x71, 0x5a, 0xe8,
	0xe6, 0x4a, 0x1a, 0x79, 0x52, 0x68, 0x54, 0x27, 0x0a, 0x27, 0x42, 0x1b, 0x54, 0x7a, 0x40, 0x41,
	0xd6, 0x91, 0xa9, 0x1c, 0xa4, 0x3a, 0x1f, 0xd8, 0x6c, 0xf7, 0x68, 0xa9, 0x72, 0x2c, 0xd3, 0x54,
	0x66, 0xae, 0x2c, 0xfa, 0x04, 0xad, 0xcb, 0xb7, 0x9c, 0xa3, 0x2e, 0xa6, 0x86, 0x31, 0x68, 0x64,
	0x71, 0x8a, 0x61, 0xad, 0x57, 0xeb, 0xb7, 0x38, 0x9d, 0xd9, 0x01, 0x34, 0xf3, 0x6f, 0x32, 0xc3,
	0xb0, 0x4e, 0x41, 0x07, 0xd8, 0x21, 0xf8, 0x98, 0x19, 0x61, 0xe6, 0xa1, 0x47, 0xe1, 0x12, 0x45,
	0xbf, 0xeb, 0x10, 0xf0, 0xc5, 0x4d, 0xde, 0x67, 0x37, 0x92, 0xed, 0x83, 0x57, 0x88, 0xa4, 0xa4,
	0xb4, 0x47, 0xb6, 0x0b, 0x75, 0x91, 0x10, 0x5d, 0x83, 0xd7, 0x45, 0x62, 0xa7, 0x9a, 0x79, 0x8e,
	0xc4, 0x14, 0x70, 0x3a, 0xb3, 0x10, 0xb6, 0xc7, 0x0a, 0x63, 0x83, 0x49, 0xd8, 0xe8, 0xd5, 0xfa,
	0x1e, 0x5f, 0x40, 0x9b, 0x29, 0xf2, 0x84, 0x32, 0x4d, 0x97, 0x29, 0x61, 0xd5, 0x23, 0x55, 0xe8,
	0xd3, 0xb4, 0x05, 0x64, 0x5d, 0xd8, 0x91, 0x39, 0x2a, 0x4a, 0x6d, 0x53, 0xaa, 0xc2, 0x95, 0xe6,
	0x9d, 0x25, 0xcd, 0x87, 0xe0, 0x2b, 0x4c, 0x63, 0x75, 0x1b, 0xb6, 0x9c, 0x3a, 0x87, 0xac, 0x17,
	0xf2, 0x3e, 0x43, 0x15, 0x82, 0xf3, 0x82, 0x80, 0x65, 0x8f, 0xc7, 0x46, 0xcc, 0xac, 0x1b, 0x6d,
	0xc7, 0xbe, 0xc0, 0xb6, 0xe3, 0xae, 0x90, 0x06, 0xc3, 0x8e, 0xeb, 0x20, 0x60, 0xa3, 0xb1, 0xd6,
	0x68, 0xc2, 0xc0, 0x45, 0x09, 0xb0, 0x53, 0xd8, 0x56, 0xb4, 0x07, 0x1d, 0xbe, 0xe8, 0x79, 0xfd,
	0xf6, 0xf0, 0x68, 0xb0, 0xbc, 0xc3, 0x41, 0xb5, 0x27, 0xbe, 0xa8, 0x8b, 0x7e, 0xd4, 0x61, 0x8f,
	0xe3, 0x5d, 0xe5, 0xf8, 0x59, 0x92, 0x6c, 0x30, 0x7c, 0x21, 0xb1, 0xbe, 0x51, 0xa2, 0xb7, 0x59,
	0x62, 0x63, 0x4d, 0x62, 0x65, 0x60, 0x73, 0xcd, 0xc0, 0x4a, 0xa2, 0xbf, 0x26, 0x71, 0x2c, 0xa7,
	0x95, 0xdf, 0x0e, 0xd8, 0xa9, 0x62, 0x92, 0x49, 0xe5, 0xec, 0x0e, 0x78, 0x89, 0xaa, 0x27, 0xd0,
	0x5a, 0x7d, 0x02, 0x26, 0x56, 0x13, 0x34, 0x3a, 0xdc, 0xeb, 0x79, 0x76, 0x9d, 0x25, 0xb4, 0xb7,
	0xb9, 0x47, 0xbc, 0x4d, 0xe2, 0xb9, 0x0e, 0xf7, 0x7b, 0x5e, 0x3f, 0xe0, 0x15, 0x8e, 0xbe, 0x03,
	0xe3, 0x98, 0x4f, 0xe7, 0xab, 0x8f, 0xf0, 0x14, 0x7c, 0x6d, 0x62, 0x53, 0x68, 0xb2, 0xa5, 0x3d,
	0x7c, 0xb9, 0xea, 0x2c, 0x75, 0x5c, 0x51, 0x01, 0x2f, 0x0b, 0xd9, 0x09, 0x34, 0x44, 0x76, 0x23,
	0xc9, 0xb4, 0xf6, 0xf0, 0x78, 0xbd, 0x61, 0x89, 0x9d, 0x53, 0x61, 0xf4, 0xb3, 0xb6, 0x3e, 0xfa,
	0xa3, 0xd0, 0xe6, 0x7f, 0x46, 0x1f, 0x40, 0xd3, 0x48, 0x13, 0x4f, 0x69, 0x76, 0xc0, 0x1d, 0xa0,
	0x0f, 0x31, 0x9e, 0xa0, 0x2e, 0xbf, 0x13, 0x07, 0xac, 0x73, 0xf6, 0x40, 0xeb, 0x0a, 0x38, 0x9d,
	0xad, 0xcb, 0x59, 0x91, 0x5e, 0xa3, 0xdb, 0x55, 0xc0, 0x4b, 0x64, 0x25, 0x4d, 0x85, 0x36, 0xe4,
	0xd9, 0x73, 0x92, 0x6c, 0xe1, 0xf0, 0x97, 0x07, 0xfb, 0x55, 0xfc, 0x0a, 0xd5, 0x4c, 0x8c, 0x91,
	0x5d, 0x80, 0x7f, 0x96, 0x24, 0x97, 0x19, 0xb2, 0xd7, 0xeb, 0x0c, 0x2b, 0x0f, 0xb1, 0xdb, 0xdb,
	0xa0, 0x74, 0x65, 0x4a, 0xb4, 0xc5, 0x46, 0xe0, 0x8f, 0xd0, 0x58, 0xb2, 0x07, 0xbe, 0xdc, 0x15,
	0xa8, 0x8d, 0x2d, 0xfb, 0x27, 0xa2, 0xcf, 0xd0, 0x1e, 0xa1, 0x39, 0x9f, 0xbf, 0x13, 0x53, 0x83,
	0x8a, 0x1d, 0x6f, 0x64, 0x73, 0xc9, 0xa7, 0xf9, 0xec, 0xd2, 0xa2, 0x2d, 0x76, 0x01, 0x9d, 0x11,
	0x1a, 0xbb, 0x18, 0xa1, 0x8d, 0x18, 0x3f, 0x4d, 0xf8, 0xea, 0x91, 0x9d, 0x52, 0x6b, 0xb4, 0xc5,
	0x3e, 0xc0, 0xee, 0x17, 0xfa, 0x91, 0xaa, 0xee, 0xf7, 0xd0, 0x3a, 0x57, 0x50, 0x12, 0x1e, 0x6d,
	0x20, 0x2c, 0x85, 0x9e, 0x41, 0x8b, 0x63, 0x2a, 0x67, 0xf8, 0x8c, 0x69, 0x8f, 0x53, 0x9c, 0x77,
	0xbe, 0xc2, 0xdf, 0xbf, 0x83, 0x6b, 0x9f, 0xce, 0x6f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x71,
	0x51, 0x83, 0x23, 0x4d, 0x06, 0x00, 0x00,
}
