// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/registers.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RegistersService service

type RegistersService interface {
	AddOne(ctx context.Context, in *ReqRegistersAdd, opts ...client.CallOption) (*ReplyRegistersInfo, error)
	GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyRegistersInfo, error)
	GetByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyRegistersList, error)
	GetStatistic(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStatistic, error)
	UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, opts ...client.CallOption) (*ReplyInfo, error)
	RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error)
}

type registersService struct {
	c    client.Client
	name string
}

func NewRegistersService(name string, c client.Client) RegistersService {
	return &registersService{
		c:    c,
		name: name,
	}
}

func (c *registersService) AddOne(ctx context.Context, in *ReqRegistersAdd, opts ...client.CallOption) (*ReplyRegistersInfo, error) {
	req := c.c.NewRequest(c.name, "RegistersService.AddOne", in)
	out := new(ReplyRegistersInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registersService) GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyRegistersInfo, error) {
	req := c.c.NewRequest(c.name, "RegistersService.GetOne", in)
	out := new(ReplyRegistersInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registersService) GetByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyRegistersList, error) {
	req := c.c.NewRequest(c.name, "RegistersService.GetByFilter", in)
	out := new(ReplyRegistersList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registersService) GetStatistic(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStatistic, error) {
	req := c.c.NewRequest(c.name, "RegistersService.GetStatistic", in)
	out := new(ReplyStatistic)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registersService) UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "RegistersService.UpdateByFilter", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registersService) RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "RegistersService.RemoveOne", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RegistersService service

type RegistersServiceHandler interface {
	AddOne(context.Context, *ReqRegistersAdd, *ReplyRegistersInfo) error
	GetOne(context.Context, *RequestInfo, *ReplyRegistersInfo) error
	GetByFilter(context.Context, *RequestFilter, *ReplyRegistersList) error
	GetStatistic(context.Context, *RequestFilter, *ReplyStatistic) error
	UpdateByFilter(context.Context, *ReqUpdateFilter, *ReplyInfo) error
	RemoveOne(context.Context, *RequestInfo, *ReplyInfo) error
}

func RegisterRegistersServiceHandler(s server.Server, hdlr RegistersServiceHandler, opts ...server.HandlerOption) error {
	type registersService interface {
		AddOne(ctx context.Context, in *ReqRegistersAdd, out *ReplyRegistersInfo) error
		GetOne(ctx context.Context, in *RequestInfo, out *ReplyRegistersInfo) error
		GetByFilter(ctx context.Context, in *RequestFilter, out *ReplyRegistersList) error
		GetStatistic(ctx context.Context, in *RequestFilter, out *ReplyStatistic) error
		UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, out *ReplyInfo) error
		RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error
	}
	type RegistersService struct {
		registersService
	}
	h := &registersServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&RegistersService{h}, opts...))
}

type registersServiceHandler struct {
	RegistersServiceHandler
}

func (h *registersServiceHandler) AddOne(ctx context.Context, in *ReqRegistersAdd, out *ReplyRegistersInfo) error {
	return h.RegistersServiceHandler.AddOne(ctx, in, out)
}

func (h *registersServiceHandler) GetOne(ctx context.Context, in *RequestInfo, out *ReplyRegistersInfo) error {
	return h.RegistersServiceHandler.GetOne(ctx, in, out)
}

func (h *registersServiceHandler) GetByFilter(ctx context.Context, in *RequestFilter, out *ReplyRegistersList) error {
	return h.RegistersServiceHandler.GetByFilter(ctx, in, out)
}

func (h *registersServiceHandler) GetStatistic(ctx context.Context, in *RequestFilter, out *ReplyStatistic) error {
	return h.RegistersServiceHandler.GetStatistic(ctx, in, out)
}

func (h *registersServiceHandler) UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, out *ReplyInfo) error {
	return h.RegistersServiceHandler.UpdateByFilter(ctx, in, out)
}

func (h *registersServiceHandler) RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error {
	return h.RegistersServiceHandler.RemoveOne(ctx, in, out)
}
