// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/staff.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StaffInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Sex                  uint32   `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Remark               string   `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	Creator              string   `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	Phone                string   `protobuf:"bytes,10,opt,name=phone,proto3" json:"phone,omitempty"`
	User                 string   `protobuf:"bytes,11,opt,name=user,proto3" json:"user,omitempty"`
	Scenes               []string `protobuf:"bytes,12,rep,name=scenes,proto3" json:"scenes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaffInfo) Reset()         { *m = StaffInfo{} }
func (m *StaffInfo) String() string { return proto.CompactTextString(m) }
func (*StaffInfo) ProtoMessage()    {}
func (*StaffInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec1d2bf994abf9e5, []int{0}
}

func (m *StaffInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaffInfo.Unmarshal(m, b)
}
func (m *StaffInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaffInfo.Marshal(b, m, deterministic)
}
func (m *StaffInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaffInfo.Merge(m, src)
}
func (m *StaffInfo) XXX_Size() int {
	return xxx_messageInfo_StaffInfo.Size(m)
}
func (m *StaffInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StaffInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StaffInfo proto.InternalMessageInfo

func (m *StaffInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *StaffInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StaffInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *StaffInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *StaffInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StaffInfo) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *StaffInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *StaffInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *StaffInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *StaffInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *StaffInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *StaffInfo) GetScenes() []string {
	if m != nil {
		return m.Scenes
	}
	return nil
}

type ReqStaffAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Scene                string   `protobuf:"bytes,5,opt,name=scene,proto3" json:"scene,omitempty"`
	User                 string   `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqStaffAdd) Reset()         { *m = ReqStaffAdd{} }
func (m *ReqStaffAdd) String() string { return proto.CompactTextString(m) }
func (*ReqStaffAdd) ProtoMessage()    {}
func (*ReqStaffAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec1d2bf994abf9e5, []int{1}
}

func (m *ReqStaffAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStaffAdd.Unmarshal(m, b)
}
func (m *ReqStaffAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStaffAdd.Marshal(b, m, deterministic)
}
func (m *ReqStaffAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStaffAdd.Merge(m, src)
}
func (m *ReqStaffAdd) XXX_Size() int {
	return xxx_messageInfo_ReqStaffAdd.Size(m)
}
func (m *ReqStaffAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStaffAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStaffAdd proto.InternalMessageInfo

func (m *ReqStaffAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqStaffAdd) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ReqStaffAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqStaffAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqStaffAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqStaffAdd) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type ReqStaffUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Sex                  uint32   `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqStaffUpdate) Reset()         { *m = ReqStaffUpdate{} }
func (m *ReqStaffUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqStaffUpdate) ProtoMessage()    {}
func (*ReqStaffUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec1d2bf994abf9e5, []int{2}
}

func (m *ReqStaffUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStaffUpdate.Unmarshal(m, b)
}
func (m *ReqStaffUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStaffUpdate.Marshal(b, m, deterministic)
}
func (m *ReqStaffUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStaffUpdate.Merge(m, src)
}
func (m *ReqStaffUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqStaffUpdate.Size(m)
}
func (m *ReqStaffUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStaffUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStaffUpdate proto.InternalMessageInfo

func (m *ReqStaffUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqStaffUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqStaffUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqStaffUpdate) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *ReqStaffUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqStaffUpdate) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ReplyStaffOne struct {
	Info                 *StaffInfo   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStaffOne) Reset()         { *m = ReplyStaffOne{} }
func (m *ReplyStaffOne) String() string { return proto.CompactTextString(m) }
func (*ReplyStaffOne) ProtoMessage()    {}
func (*ReplyStaffOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec1d2bf994abf9e5, []int{3}
}

func (m *ReplyStaffOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStaffOne.Unmarshal(m, b)
}
func (m *ReplyStaffOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStaffOne.Marshal(b, m, deterministic)
}
func (m *ReplyStaffOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStaffOne.Merge(m, src)
}
func (m *ReplyStaffOne) XXX_Size() int {
	return xxx_messageInfo_ReplyStaffOne.Size(m)
}
func (m *ReplyStaffOne) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStaffOne.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStaffOne proto.InternalMessageInfo

func (m *ReplyStaffOne) GetInfo() *StaffInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyStaffOne) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyStaffList struct {
	Total                uint64       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32       `protobuf:"varint,2,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32       `protobuf:"varint,3,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*StaffInfo `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStaffList) Reset()         { *m = ReplyStaffList{} }
func (m *ReplyStaffList) String() string { return proto.CompactTextString(m) }
func (*ReplyStaffList) ProtoMessage()    {}
func (*ReplyStaffList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec1d2bf994abf9e5, []int{4}
}

func (m *ReplyStaffList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStaffList.Unmarshal(m, b)
}
func (m *ReplyStaffList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStaffList.Marshal(b, m, deterministic)
}
func (m *ReplyStaffList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStaffList.Merge(m, src)
}
func (m *ReplyStaffList) XXX_Size() int {
	return xxx_messageInfo_ReplyStaffList.Size(m)
}
func (m *ReplyStaffList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStaffList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStaffList proto.InternalMessageInfo

func (m *ReplyStaffList) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyStaffList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyStaffList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyStaffList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyStaffList) GetList() []*StaffInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*StaffInfo)(nil), "omo.msp.user.StaffInfo")
	proto.RegisterType((*ReqStaffAdd)(nil), "omo.msp.user.ReqStaffAdd")
	proto.RegisterType((*ReqStaffUpdate)(nil), "omo.msp.user.ReqStaffUpdate")
	proto.RegisterType((*ReplyStaffOne)(nil), "omo.msp.user.ReplyStaffOne")
	proto.RegisterType((*ReplyStaffList)(nil), "omo.msp.user.ReplyStaffList")
}

func init() {
	proto.RegisterFile("proto/user/staff.proto", fileDescriptor_ec1d2bf994abf9e5)
}

var fileDescriptor_ec1d2bf994abf9e5 = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0xeb, 0x43, 0xdd, 0x66, 0xe2, 0x44, 0x9f, 0x56, 0x9f, 0x9a, 0x25, 0x14, 0xc9, 0xf2,
	0x55, 0x24, 0xa4, 0x54, 0x84, 0x27, 0x68, 0x84, 0xa8, 0xca, 0xa1, 0x20, 0x57, 0xdc, 0x70, 0x67,
	0xe2, 0x4d, 0xb1, 0x88, 0xbd, 0xae, 0x77, 0x4d, 0xdb, 0xd7, 0x40, 0x42, 0xbc, 0x0b, 0x2f, 0xc0,
	0x6b, 0xa1, 0x99, 0xb5, 0x1d, 0x57, 0x49, 0x5a, 0xee, 0x76, 0x32, 0xe3, 0xff, 0xff, 0x37, 0x07,
	0x05, 0x8e, 0x8a, 0x52, 0x6a, 0x79, 0x52, 0x29, 0x51, 0x9e, 0x28, 0x1d, 0x2f, 0x97, 0x53, 0xfa,
	0x81, 0xf9, 0x32, 0x93, 0xd3, 0x4c, 0x15, 0x53, 0xcc, 0x8c, 0x47, 0x9d, 0xaa, 0x85, 0xcc, 0x32,
	0x99, 0x9b, 0xb2, 0xf0, 0x97, 0x0d, 0xbd, 0x4b, 0xfc, 0xec, 0x3c, 0x5f, 0x4a, 0xf6, 0x1f, 0x38,
	0x55, 0x9a, 0x70, 0x2b, 0xb0, 0x26, 0xbd, 0x08, 0x9f, 0x6c, 0x08, 0x76, 0x9a, 0x70, 0x3b, 0xb0,
	0x26, 0x6e, 0x64, 0xa7, 0x09, 0xe3, 0x70, 0xb0, 0x28, 0x45, 0xac, 0x45, 0xc2, 0x9d, 0xc0, 0x9a,
	0x38, 0x51, 0x13, 0x62, 0xa6, 0x2a, 0x12, 0xca, 0xb8, 0x26, 0x53, 0x87, 0x8c, 0x81, 0x9b, 0xc7,
	0x99, 0xe0, 0xfb, 0x24, 0x4b, 0x6f, 0x74, 0x52, 0xe2, 0x96, 0x7b, 0x81, 0x35, 0x19, 0x44, 0xf8,
	0x64, 0x47, 0xe0, 0x95, 0x22, 0x8b, 0xcb, 0x6f, 0xfc, 0x80, 0xea, 0xea, 0xa8, 0x75, 0x94, 0x25,
	0x3f, 0xa4, 0x44, 0x13, 0xb2, 0x31, 0x1c, 0xca, 0x42, 0x94, 0x94, 0xea, 0x51, 0xaa, 0x8d, 0xd9,
	0xff, 0xb0, 0x5f, 0x7c, 0x95, 0xb9, 0xe0, 0x40, 0x09, 0x13, 0x20, 0x09, 0x8e, 0x80, 0xf7, 0x0d,
	0x09, 0xbe, 0xd1, 0x57, 0x2d, 0x44, 0x2e, 0x14, 0xf7, 0x03, 0x07, 0x7d, 0x4d, 0x14, 0xfe, 0xb4,
	0xa0, 0x1f, 0x89, 0x6b, 0x1a, 0xce, 0x69, 0xb2, 0xee, 0xc2, 0xea, 0x74, 0xd1, 0xba, 0xd8, 0x5d,
	0x97, 0x75, 0x27, 0xce, 0xbd, 0x4e, 0xba, 0xbc, 0xee, 0x26, 0x2f, 0xf9, 0xd6, 0x43, 0x32, 0x41,
	0xcb, 0xeb, 0xad, 0x79, 0xc3, 0x1f, 0x16, 0x0c, 0x1b, 0xae, 0x4f, 0x34, 0xe1, 0x2d, 0x6b, 0x6b,
	0x60, 0xed, 0x0e, 0xec, 0x2e, 0xac, 0x7a, 0x15, 0xee, 0x7a, 0x15, 0x5d, 0xd0, 0xfd, 0x5d, 0x83,
	0xf5, 0x3a, 0x2d, 0x87, 0x12, 0x06, 0x91, 0x28, 0x56, 0x77, 0x44, 0xf5, 0x21, 0x17, 0xec, 0x39,
	0xb8, 0x69, 0xbe, 0x94, 0xc4, 0xd4, 0x9f, 0x8d, 0xa6, 0xdd, 0x6b, 0x9c, 0xb6, 0x07, 0x17, 0x51,
	0x11, 0x7b, 0x01, 0x9e, 0xd2, 0xb1, 0xae, 0x14, 0xf1, 0xf6, 0x67, 0x4f, 0xee, 0x97, 0x37, 0xca,
	0xba, 0x52, 0x51, 0x5d, 0x18, 0xfe, 0xa6, 0x29, 0x34, 0x8e, 0xef, 0x52, 0xa5, 0x91, 0x4c, 0x4b,
	0x1d, 0xaf, 0xc8, 0xd3, 0x8d, 0x4c, 0x80, 0xe7, 0x53, 0xc4, 0x57, 0xe2, 0x7d, 0x7c, 0x4b, 0xe2,
	0x83, 0xa8, 0x09, 0x9b, 0xcc, 0x85, 0xbc, 0xa1, 0x81, 0xd4, 0x99, 0x0b, 0x79, 0xd3, 0xe1, 0x71,
	0xff, 0x91, 0x07, 0xfb, 0x5d, 0xa5, 0x4a, 0xf3, 0x7e, 0xe0, 0x3c, 0xd8, 0x2f, 0x16, 0xcd, 0xfe,
	0x38, 0xe0, 0xd3, 0x6f, 0x97, 0xa2, 0xfc, 0x9e, 0x2e, 0x04, 0x9b, 0x83, 0x77, 0x9a, 0x24, 0x38,
	0xb7, 0x0d, 0xab, 0xf6, 0x00, 0xc7, 0x4f, 0xb7, 0x53, 0xd0, 0xbc, 0xc3, 0x3d, 0xf6, 0x0a, 0xbc,
	0x33, 0xa1, 0x51, 0x63, 0xa3, 0xf0, 0xba, 0x12, 0x4a, 0xbf, 0x4e, 0x57, 0x5a, 0x94, 0x8f, 0xa9,
	0x9c, 0x03, 0x98, 0xa3, 0x9a, 0xc7, 0x4a, 0xb0, 0xe3, 0xed, 0x34, 0xa6, 0xe2, 0x31, 0xa9, 0xb7,
	0xe0, 0xe3, 0x5e, 0xe6, 0x77, 0xc6, 0xf9, 0x61, 0xac, 0xe3, 0x5d, 0x5a, 0x28, 0x11, 0xee, 0xb1,
	0x37, 0x30, 0xac, 0xb9, 0x1a, 0xb9, 0x67, 0x1b, 0x72, 0xa6, 0xa0, 0x16, 0x1c, 0x6d, 0x11, 0xc4,
	0x15, 0x50, 0x8f, 0xfe, 0x99, 0xd0, 0xb8, 0xc0, 0x54, 0xe9, 0x74, 0xb1, 0x65, 0xe6, 0x08, 0xf6,
	0x31, 0xbe, 0x12, 0xbb, 0xb0, 0xcc, 0x87, 0xe1, 0xde, 0xdc, 0xff, 0x0c, 0xeb, 0x7f, 0xd6, 0x2f,
	0x1e, 0xbd, 0x5f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x78, 0xde, 0x40, 0xc7, 0x94, 0x05, 0x00,
	0x00,
}
