// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/staff.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StaffService service

type StaffService interface {
	AddOne(ctx context.Context, in *ReqStaffAdd, opts ...client.CallOption) (*ReplyStaffOne, error)
	GetOne(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStaffOne, error)
	UpdateBase(ctx context.Context, in *ReqStaffUpdate, opts ...client.CallOption) (*ReplyStaffOne, error)
	ListByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStaffList, error)
	UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, opts ...client.CallOption) (*ReplyInfo, error)
	GetStatistic(ctx context.Context, in *RequestPage, opts ...client.CallOption) (*ReplyStatistic, error)
}

type staffService struct {
	c    client.Client
	name string
}

func NewStaffService(name string, c client.Client) StaffService {
	return &staffService{
		c:    c,
		name: name,
	}
}

func (c *staffService) AddOne(ctx context.Context, in *ReqStaffAdd, opts ...client.CallOption) (*ReplyStaffOne, error) {
	req := c.c.NewRequest(c.name, "StaffService.AddOne", in)
	out := new(ReplyStaffOne)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffService) GetOne(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStaffOne, error) {
	req := c.c.NewRequest(c.name, "StaffService.GetOne", in)
	out := new(ReplyStaffOne)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffService) UpdateBase(ctx context.Context, in *ReqStaffUpdate, opts ...client.CallOption) (*ReplyStaffOne, error) {
	req := c.c.NewRequest(c.name, "StaffService.UpdateBase", in)
	out := new(ReplyStaffOne)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffService) ListByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStaffList, error) {
	req := c.c.NewRequest(c.name, "StaffService.ListByFilter", in)
	out := new(ReplyStaffList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffService) UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "StaffService.UpdateByFilter", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffService) GetStatistic(ctx context.Context, in *RequestPage, opts ...client.CallOption) (*ReplyStatistic, error) {
	req := c.c.NewRequest(c.name, "StaffService.GetStatistic", in)
	out := new(ReplyStatistic)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StaffService service

type StaffServiceHandler interface {
	AddOne(context.Context, *ReqStaffAdd, *ReplyStaffOne) error
	GetOne(context.Context, *RequestFilter, *ReplyStaffOne) error
	UpdateBase(context.Context, *ReqStaffUpdate, *ReplyStaffOne) error
	ListByFilter(context.Context, *RequestFilter, *ReplyStaffList) error
	UpdateByFilter(context.Context, *ReqUpdateFilter, *ReplyInfo) error
	GetStatistic(context.Context, *RequestPage, *ReplyStatistic) error
}

func RegisterStaffServiceHandler(s server.Server, hdlr StaffServiceHandler, opts ...server.HandlerOption) error {
	type staffService interface {
		AddOne(ctx context.Context, in *ReqStaffAdd, out *ReplyStaffOne) error
		GetOne(ctx context.Context, in *RequestFilter, out *ReplyStaffOne) error
		UpdateBase(ctx context.Context, in *ReqStaffUpdate, out *ReplyStaffOne) error
		ListByFilter(ctx context.Context, in *RequestFilter, out *ReplyStaffList) error
		UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, out *ReplyInfo) error
		GetStatistic(ctx context.Context, in *RequestPage, out *ReplyStatistic) error
	}
	type StaffService struct {
		staffService
	}
	h := &staffServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StaffService{h}, opts...))
}

type staffServiceHandler struct {
	StaffServiceHandler
}

func (h *staffServiceHandler) AddOne(ctx context.Context, in *ReqStaffAdd, out *ReplyStaffOne) error {
	return h.StaffServiceHandler.AddOne(ctx, in, out)
}

func (h *staffServiceHandler) GetOne(ctx context.Context, in *RequestFilter, out *ReplyStaffOne) error {
	return h.StaffServiceHandler.GetOne(ctx, in, out)
}

func (h *staffServiceHandler) UpdateBase(ctx context.Context, in *ReqStaffUpdate, out *ReplyStaffOne) error {
	return h.StaffServiceHandler.UpdateBase(ctx, in, out)
}

func (h *staffServiceHandler) ListByFilter(ctx context.Context, in *RequestFilter, out *ReplyStaffList) error {
	return h.StaffServiceHandler.ListByFilter(ctx, in, out)
}

func (h *staffServiceHandler) UpdateByFilter(ctx context.Context, in *ReqUpdateFilter, out *ReplyInfo) error {
	return h.StaffServiceHandler.UpdateByFilter(ctx, in, out)
}

func (h *staffServiceHandler) GetStatistic(ctx context.Context, in *RequestPage, out *ReplyStatistic) error {
	return h.StaffServiceHandler.GetStatistic(ctx, in, out)
}
