// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserSex int32

const (
	UserSex_Girl UserSex = 0
	UserSex_Boy  UserSex = 1
)

var UserSex_name = map[int32]string{
	0: "Girl",
	1: "Boy",
}

var UserSex_value = map[string]int32{
	"Girl": 0,
	"Boy":  1,
}

func (x UserSex) String() string {
	return proto.EnumName(UserSex_name, int32(x))
}

func (UserSex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

type UserType int32

const (
	UserType_SuperRoot        UserType = 0
	UserType_EnterpriseAdmin  UserType = 1
	UserType_EnterpriseCommon UserType = 2
	UserType_Common           UserType = 3
	UserType_Visitor          UserType = 4
)

var UserType_name = map[int32]string{
	0: "SuperRoot",
	1: "EnterpriseAdmin",
	2: "EnterpriseCommon",
	3: "Common",
	4: "Visitor",
}

var UserType_value = map[string]int32{
	"SuperRoot":        0,
	"EnterpriseAdmin":  1,
	"EnterpriseCommon": 2,
	"Common":           3,
	"Visitor":          4,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

type SNSInfo struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SNSInfo) Reset()         { *m = SNSInfo{} }
func (m *SNSInfo) String() string { return proto.CompactTextString(m) }
func (*SNSInfo) ProtoMessage()    {}
func (*SNSInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *SNSInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SNSInfo.Unmarshal(m, b)
}
func (m *SNSInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SNSInfo.Marshal(b, m, deterministic)
}
func (m *SNSInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SNSInfo.Merge(m, src)
}
func (m *SNSInfo) XXX_Size() int {
	return xxx_messageInfo_SNSInfo.Size(m)
}
func (m *SNSInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SNSInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SNSInfo proto.InternalMessageInfo

func (m *SNSInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *SNSInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SNSInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type UserInfo struct {
	Uid                  string     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 UserType   `protobuf:"varint,3,opt,name=type,proto3,enum=omo.msp.user.UserType" json:"type,omitempty"`
	Created              int64      `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64      `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Name                 string     `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Account              string     `protobuf:"bytes,7,opt,name=account,proto3" json:"account,omitempty"`
	Sex                  UserSex    `protobuf:"varint,8,opt,name=sex,proto3,enum=omo.msp.user.UserSex" json:"sex,omitempty"`
	Nick                 string     `protobuf:"bytes,9,opt,name=nick,proto3" json:"nick,omitempty"`
	Remark               string     `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	Creator              string     `protobuf:"bytes,12,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string     `protobuf:"bytes,13,opt,name=operator,proto3" json:"operator,omitempty"`
	Phone                string     `protobuf:"bytes,14,opt,name=phone,proto3" json:"phone,omitempty"`
	Entity               string     `protobuf:"bytes,15,opt,name=entity,proto3" json:"entity,omitempty"`
	Portrait             string     `protobuf:"bytes,16,opt,name=portrait,proto3" json:"portrait,omitempty"`
	Tags                 []string   `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty"`
	Sns                  []*SNSInfo `protobuf:"bytes,18,rep,name=sns,proto3" json:"sns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetType() UserType {
	if m != nil {
		return m.Type
	}
	return UserType_SuperRoot
}

func (m *UserInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *UserInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserInfo) GetSex() UserSex {
	if m != nil {
		return m.Sex
	}
	return UserSex_Girl
}

func (m *UserInfo) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *UserInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *UserInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *UserInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *UserInfo) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

func (m *UserInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *UserInfo) GetSns() []*SNSInfo {
	if m != nil {
		return m.Sns
	}
	return nil
}

type ReqUserAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex                  UserSex  `protobuf:"varint,2,opt,name=sex,proto3,enum=omo.msp.user.UserSex" json:"sex,omitempty"`
	Type                 UserType `protobuf:"varint,3,opt,name=type,proto3,enum=omo.msp.user.UserType" json:"type,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Remark               string   `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	Nick                 string   `protobuf:"bytes,7,opt,name=nick,proto3" json:"nick,omitempty"`
	Operator             string   `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	Passwords            string   `protobuf:"bytes,9,opt,name=passwords,proto3" json:"passwords,omitempty"`
	Entity               string   `protobuf:"bytes,10,opt,name=entity,proto3" json:"entity,omitempty"`
	Portrait             string   `protobuf:"bytes,11,opt,name=portrait,proto3" json:"portrait,omitempty"`
	Sns                  *SNSInfo `protobuf:"bytes,12,opt,name=sns,proto3" json:"sns,omitempty"`
	Tags                 []string `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserAdd) Reset()         { *m = ReqUserAdd{} }
func (m *ReqUserAdd) String() string { return proto.CompactTextString(m) }
func (*ReqUserAdd) ProtoMessage()    {}
func (*ReqUserAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *ReqUserAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserAdd.Unmarshal(m, b)
}
func (m *ReqUserAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserAdd.Marshal(b, m, deterministic)
}
func (m *ReqUserAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserAdd.Merge(m, src)
}
func (m *ReqUserAdd) XXX_Size() int {
	return xxx_messageInfo_ReqUserAdd.Size(m)
}
func (m *ReqUserAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserAdd proto.InternalMessageInfo

func (m *ReqUserAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqUserAdd) GetSex() UserSex {
	if m != nil {
		return m.Sex
	}
	return UserSex_Girl
}

func (m *ReqUserAdd) GetType() UserType {
	if m != nil {
		return m.Type
	}
	return UserType_SuperRoot
}

func (m *ReqUserAdd) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ReqUserAdd) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ReqUserAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqUserAdd) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *ReqUserAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqUserAdd) GetPasswords() string {
	if m != nil {
		return m.Passwords
	}
	return ""
}

func (m *ReqUserAdd) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *ReqUserAdd) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

func (m *ReqUserAdd) GetSns() *SNSInfo {
	if m != nil {
		return m.Sns
	}
	return nil
}

func (m *ReqUserAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqUserBy struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type                 uint32   `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserBy) Reset()         { *m = ReqUserBy{} }
func (m *ReqUserBy) String() string { return proto.CompactTextString(m) }
func (*ReqUserBy) ProtoMessage()    {}
func (*ReqUserBy) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *ReqUserBy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserBy.Unmarshal(m, b)
}
func (m *ReqUserBy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserBy.Marshal(b, m, deterministic)
}
func (m *ReqUserBy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserBy.Merge(m, src)
}
func (m *ReqUserBy) XXX_Size() int {
	return xxx_messageInfo_ReqUserBy.Size(m)
}
func (m *ReqUserBy) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserBy.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserBy proto.InternalMessageInfo

func (m *ReqUserBy) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqUserBy) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type ReqUserSearch struct {
	Type                 UserType `protobuf:"varint,1,opt,name=type,proto3,enum=omo.msp.user.UserType" json:"type,omitempty"`
	Tags                 []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserSearch) Reset()         { *m = ReqUserSearch{} }
func (m *ReqUserSearch) String() string { return proto.CompactTextString(m) }
func (*ReqUserSearch) ProtoMessage()    {}
func (*ReqUserSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *ReqUserSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserSearch.Unmarshal(m, b)
}
func (m *ReqUserSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserSearch.Marshal(b, m, deterministic)
}
func (m *ReqUserSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserSearch.Merge(m, src)
}
func (m *ReqUserSearch) XXX_Size() int {
	return xxx_messageInfo_ReqUserSearch.Size(m)
}
func (m *ReqUserSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserSearch.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserSearch proto.InternalMessageInfo

func (m *ReqUserSearch) GetType() UserType {
	if m != nil {
		return m.Type
	}
	return UserType_SuperRoot
}

func (m *ReqUserSearch) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqUserUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Job                  string   `protobuf:"bytes,5,opt,name=job,proto3" json:"job,omitempty"`
	Remark               string   `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	Sex                  UserSex  `protobuf:"varint,7,opt,name=sex,proto3,enum=omo.msp.user.UserSex" json:"sex,omitempty"`
	Operator             string   `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	Portrait             string   `protobuf:"bytes,9,opt,name=portrait,proto3" json:"portrait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserUpdate) Reset()         { *m = ReqUserUpdate{} }
func (m *ReqUserUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqUserUpdate) ProtoMessage()    {}
func (*ReqUserUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *ReqUserUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserUpdate.Unmarshal(m, b)
}
func (m *ReqUserUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserUpdate.Marshal(b, m, deterministic)
}
func (m *ReqUserUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserUpdate.Merge(m, src)
}
func (m *ReqUserUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqUserUpdate.Size(m)
}
func (m *ReqUserUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserUpdate proto.InternalMessageInfo

func (m *ReqUserUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqUserUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqUserUpdate) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *ReqUserUpdate) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ReqUserUpdate) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *ReqUserUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqUserUpdate) GetSex() UserSex {
	if m != nil {
		return m.Sex
	}
	return UserSex_Girl
}

func (m *ReqUserUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqUserUpdate) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

type ReqUserSNS struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Add                  bool     `protobuf:"varint,2,opt,name=add,proto3" json:"add,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Uid                  string   `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserSNS) Reset()         { *m = ReqUserSNS{} }
func (m *ReqUserSNS) String() string { return proto.CompactTextString(m) }
func (*ReqUserSNS) ProtoMessage()    {}
func (*ReqUserSNS) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{6}
}

func (m *ReqUserSNS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserSNS.Unmarshal(m, b)
}
func (m *ReqUserSNS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserSNS.Marshal(b, m, deterministic)
}
func (m *ReqUserSNS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserSNS.Merge(m, src)
}
func (m *ReqUserSNS) XXX_Size() int {
	return xxx_messageInfo_ReqUserSNS.Size(m)
}
func (m *ReqUserSNS) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserSNS.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserSNS proto.InternalMessageInfo

func (m *ReqUserSNS) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReqUserSNS) GetAdd() bool {
	if m != nil {
		return m.Add
	}
	return false
}

func (m *ReqUserSNS) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqUserSNS) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqUserSNS) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqUserSNS) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqUserEntity struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Entity               string   `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserEntity) Reset()         { *m = ReqUserEntity{} }
func (m *ReqUserEntity) String() string { return proto.CompactTextString(m) }
func (*ReqUserEntity) ProtoMessage()    {}
func (*ReqUserEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{7}
}

func (m *ReqUserEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserEntity.Unmarshal(m, b)
}
func (m *ReqUserEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserEntity.Marshal(b, m, deterministic)
}
func (m *ReqUserEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserEntity.Merge(m, src)
}
func (m *ReqUserEntity) XXX_Size() int {
	return xxx_messageInfo_ReqUserEntity.Size(m)
}
func (m *ReqUserEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserEntity.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserEntity proto.InternalMessageInfo

func (m *ReqUserEntity) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqUserEntity) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

type ReqUserTags struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserTags) Reset()         { *m = ReqUserTags{} }
func (m *ReqUserTags) String() string { return proto.CompactTextString(m) }
func (*ReqUserTags) ProtoMessage()    {}
func (*ReqUserTags) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{8}
}

func (m *ReqUserTags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserTags.Unmarshal(m, b)
}
func (m *ReqUserTags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserTags.Marshal(b, m, deterministic)
}
func (m *ReqUserTags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserTags.Merge(m, src)
}
func (m *ReqUserTags) XXX_Size() int {
	return xxx_messageInfo_ReqUserTags.Size(m)
}
func (m *ReqUserTags) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserTags.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserTags proto.InternalMessageInfo

func (m *ReqUserTags) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqUserTags) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqUserTags) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReplyUserOne struct {
	Info                 *UserInfo    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyUserOne) Reset()         { *m = ReplyUserOne{} }
func (m *ReplyUserOne) String() string { return proto.CompactTextString(m) }
func (*ReplyUserOne) ProtoMessage()    {}
func (*ReplyUserOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{9}
}

func (m *ReplyUserOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyUserOne.Unmarshal(m, b)
}
func (m *ReplyUserOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyUserOne.Marshal(b, m, deterministic)
}
func (m *ReplyUserOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyUserOne.Merge(m, src)
}
func (m *ReplyUserOne) XXX_Size() int {
	return xxx_messageInfo_ReplyUserOne.Size(m)
}
func (m *ReplyUserOne) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyUserOne.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyUserOne proto.InternalMessageInfo

func (m *ReplyUserOne) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyUserOne) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReqUserList struct {
	List                 []string `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUserList) Reset()         { *m = ReqUserList{} }
func (m *ReqUserList) String() string { return proto.CompactTextString(m) }
func (*ReqUserList) ProtoMessage()    {}
func (*ReqUserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{10}
}

func (m *ReqUserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUserList.Unmarshal(m, b)
}
func (m *ReqUserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUserList.Marshal(b, m, deterministic)
}
func (m *ReqUserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUserList.Merge(m, src)
}
func (m *ReqUserList) XXX_Size() int {
	return xxx_messageInfo_ReqUserList.Size(m)
}
func (m *ReqUserList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUserList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUserList proto.InternalMessageInfo

func (m *ReqUserList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyUserList struct {
	Total                uint64       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32       `protobuf:"varint,2,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32       `protobuf:"varint,3,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	List                 []*UserInfo  `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyUserList) Reset()         { *m = ReplyUserList{} }
func (m *ReplyUserList) String() string { return proto.CompactTextString(m) }
func (*ReplyUserList) ProtoMessage()    {}
func (*ReplyUserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{11}
}

func (m *ReplyUserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyUserList.Unmarshal(m, b)
}
func (m *ReplyUserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyUserList.Marshal(b, m, deterministic)
}
func (m *ReplyUserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyUserList.Merge(m, src)
}
func (m *ReplyUserList) XXX_Size() int {
	return xxx_messageInfo_ReplyUserList.Size(m)
}
func (m *ReplyUserList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyUserList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyUserList proto.InternalMessageInfo

func (m *ReplyUserList) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyUserList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyUserList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyUserList) GetList() []*UserInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyUserList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("omo.msp.user.UserSex", UserSex_name, UserSex_value)
	proto.RegisterEnum("omo.msp.user.UserType", UserType_name, UserType_value)
	proto.RegisterType((*SNSInfo)(nil), "omo.msp.user.SNSInfo")
	proto.RegisterType((*UserInfo)(nil), "omo.msp.user.UserInfo")
	proto.RegisterType((*ReqUserAdd)(nil), "omo.msp.user.ReqUserAdd")
	proto.RegisterType((*ReqUserBy)(nil), "omo.msp.user.ReqUserBy")
	proto.RegisterType((*ReqUserSearch)(nil), "omo.msp.user.ReqUserSearch")
	proto.RegisterType((*ReqUserUpdate)(nil), "omo.msp.user.ReqUserUpdate")
	proto.RegisterType((*ReqUserSNS)(nil), "omo.msp.user.ReqUserSNS")
	proto.RegisterType((*ReqUserEntity)(nil), "omo.msp.user.ReqUserEntity")
	proto.RegisterType((*ReqUserTags)(nil), "omo.msp.user.ReqUserTags")
	proto.RegisterType((*ReplyUserOne)(nil), "omo.msp.user.ReplyUserOne")
	proto.RegisterType((*ReqUserList)(nil), "omo.msp.user.ReqUserList")
	proto.RegisterType((*ReplyUserList)(nil), "omo.msp.user.ReplyUserList")
}

func init() {
	proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7)
}

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 1019 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xbd, 0x72, 0xdb, 0x46,
	0x10, 0x16, 0x00, 0x92, 0x20, 0x97, 0xa2, 0x8d, 0x5c, 0x64, 0x0b, 0xa6, 0x5d, 0x30, 0x68, 0xa2,
	0x51, 0xc1, 0x8c, 0x95, 0x2a, 0x5d, 0x48, 0x49, 0xd6, 0x68, 0x92, 0x50, 0x19, 0xc0, 0x4e, 0x91,
	0x99, 0x14, 0x30, 0x71, 0x96, 0x11, 0x89, 0x38, 0x18, 0x00, 0x6d, 0xf1, 0x0d, 0xf2, 0x48, 0x79,
	0x88, 0xbc, 0x44, 0x5e, 0x21, 0x75, 0x8a, 0xcc, 0xee, 0x1d, 0x7e, 0x48, 0x82, 0x82, 0xe2, 0x46,
	0x73, 0x7b, 0x7b, 0xfc, 0xee, 0xdb, 0xef, 0xdb, 0x5b, 0x08, 0x9e, 0xc4, 0x89, 0xc8, 0xc4, 0x37,
	0xcb, 0x94, 0x27, 0xf4, 0x67, 0x4c, 0x31, 0xdb, 0x17, 0x0b, 0x31, 0x5e, 0xa4, 0xf1, 0x18, 0xf7,
	0x86, 0x87, 0x95, 0x43, 0x73, 0xb1, 0x58, 0x88, 0x48, 0x1e, 0x73, 0x4e, 0xc1, 0xf4, 0x66, 0xde,
	0x65, 0xf4, 0x4e, 0x30, 0x06, 0xad, 0x6c, 0x15, 0x73, 0x5b, 0x1b, 0x69, 0x47, 0x03, 0x97, 0xd6,
	0xb8, 0x17, 0xf9, 0x0b, 0x6e, 0xeb, 0x23, 0xed, 0xa8, 0xe7, 0xd2, 0x9a, 0x59, 0x60, 0x2c, 0xc3,
	0xc0, 0x36, 0x68, 0x0b, 0x97, 0xce, 0x5f, 0x06, 0x74, 0xdf, 0xa4, 0x3c, 0x21, 0x18, 0x95, 0xd6,
	0x8a, 0x34, 0x7b, 0x04, 0x7a, 0x18, 0x10, 0x44, 0xcb, 0xd5, 0xc3, 0x80, 0x1d, 0xab, 0x8b, 0x10,
	0xe1, 0xd1, 0xc9, 0xd3, 0x71, 0x95, 0xe9, 0x18, 0x71, 0x5e, 0xaf, 0x62, 0xae, 0x08, 0xd8, 0x60,
	0xce, 0x13, 0xee, 0x67, 0x3c, 0xb0, 0x5b, 0x23, 0xed, 0xc8, 0x70, 0xf3, 0x10, 0x33, 0xcb, 0x38,
	0xa0, 0x4c, 0x5b, 0x66, 0x54, 0x58, 0x90, 0xee, 0x54, 0x48, 0xdb, 0x60, 0xfa, 0xf3, 0xb9, 0x58,
	0x46, 0x99, 0x6d, 0xd2, 0x76, 0x1e, 0xb2, 0xaf, 0xc1, 0x48, 0xf9, 0x9d, 0xdd, 0x25, 0x32, 0x4f,
	0xb6, 0xc9, 0x78, 0xfc, 0xce, 0xc5, 0x13, 0x04, 0x1b, 0xce, 0x6f, 0xec, 0x9e, 0x82, 0x0d, 0xe7,
	0x37, 0xec, 0x29, 0x74, 0x12, 0xbe, 0xf0, 0x93, 0x1b, 0xbb, 0x4f, 0xbb, 0x2a, 0x2a, 0x68, 0x8b,
	0xc4, 0xde, 0x97, 0xd7, 0xa9, 0x90, 0x0d, 0xa1, 0x2b, 0x62, 0x9e, 0x50, 0x6a, 0x40, 0xa9, 0x22,
	0x66, 0x07, 0xd0, 0x8e, 0xdf, 0x8b, 0x88, 0xdb, 0x8f, 0x28, 0x21, 0x03, 0xbc, 0x83, 0x47, 0x59,
	0x98, 0xad, 0xec, 0xc7, 0xf2, 0x0e, 0x19, 0x21, 0x52, 0x2c, 0x92, 0x2c, 0xf1, 0xc3, 0xcc, 0xb6,
	0x24, 0x52, 0x1e, 0x93, 0x97, 0xfe, 0x75, 0x6a, 0x7f, 0x31, 0x32, 0x90, 0x2b, 0xae, 0xa9, 0xd0,
	0x28, 0xb5, 0xd9, 0xc8, 0x38, 0xea, 0x6f, 0x16, 0xaa, 0x7a, 0xc0, 0xc5, 0x13, 0xce, 0xbf, 0x3a,
	0x80, 0xcb, 0x3f, 0x60, 0xf1, 0x93, 0xa0, 0x94, 0x53, 0xab, 0xc8, 0xa9, 0x44, 0xd3, 0x1b, 0x45,
	0xfb, 0x9f, 0x5e, 0xe7, 0x1e, 0xb5, 0xd6, 0x3d, 0x2a, 0x84, 0x69, 0x6f, 0x08, 0xa3, 0xc4, 0xef,
	0xac, 0x89, 0x9f, 0x1b, 0x65, 0x56, 0x8c, 0xaa, 0xca, 0xde, 0xdd, 0x90, 0xfd, 0x05, 0xf4, 0x62,
	0x3f, 0x4d, 0x3f, 0x89, 0x24, 0x48, 0x95, 0xbb, 0xe5, 0x46, 0x45, 0x7e, 0xd8, 0x29, 0x7f, 0x7f,
	0x43, 0x7e, 0x25, 0x35, 0x5a, 0x7f, 0xaf, 0xd4, 0x85, 0x4f, 0x83, 0xd2, 0x27, 0xe7, 0x25, 0xf4,
	0x94, 0xfa, 0xd3, 0x55, 0xcd, 0x6b, 0xca, 0x9f, 0xa9, 0x5e, 0x3e, 0x53, 0xe7, 0x0a, 0x06, 0xea,
	0x27, 0x1e, 0xf7, 0x93, 0xf9, 0xfb, 0x42, 0x76, 0xed, 0x01, 0xb2, 0xe7, 0x1c, 0xf4, 0x0a, 0x87,
	0x7f, 0xb4, 0x02, 0xf1, 0x0d, 0xbd, 0xaa, 0x7a, 0x22, 0x5b, 0xb3, 0x61, 0x08, 0x5d, 0x94, 0x7b,
	0x86, 0xfb, 0x72, 0x40, 0x14, 0x71, 0x69, 0x62, 0xab, 0x6a, 0xa2, 0x05, 0xc6, 0xef, 0xe2, 0xad,
	0x32, 0x16, 0x97, 0x3b, 0x6d, 0x55, 0x3d, 0x67, 0x36, 0xf6, 0xdc, 0x7d, 0x5e, 0x57, 0x5d, 0xeb,
	0xad, 0xbb, 0xe6, 0xfc, 0xa1, 0x15, 0x7d, 0xef, 0xcd, 0x3c, 0xac, 0x0f, 0xb1, 0xf3, 0xbe, 0xc7,
	0x35, 0xb2, 0xf5, 0x03, 0x39, 0xcb, 0xba, 0x2e, 0x2e, 0x0b, 0x3b, 0x8c, 0x9a, 0xa9, 0xd9, 0xda,
	0x9e, 0x9a, 0xed, 0x52, 0xbf, 0x2a, 0xcd, 0xce, 0x3a, 0x4d, 0xe7, 0xbb, 0x42, 0xfe, 0x73, 0xd9,
	0x6d, 0xdb, 0xf2, 0x97, 0x7d, 0xa9, 0x57, 0xfb, 0xd2, 0xb9, 0x82, 0xbe, 0xfa, 0xe9, 0x6b, 0x7c,
	0xf5, 0xdb, 0x3f, 0xac, 0xde, 0xab, 0x6f, 0xc8, 0x93, 0xf7, 0x82, 0x51, 0xe9, 0x85, 0x05, 0xec,
	0xbb, 0x3c, 0xbe, 0x5d, 0x21, 0xe4, 0x55, 0xc4, 0xb1, 0xb7, 0xc2, 0xe8, 0x9d, 0x20, 0xc8, 0x7e,
	0x5d, 0x6f, 0x51, 0x7b, 0xd3, 0x19, 0xf6, 0x12, 0x3a, 0x69, 0xe6, 0x67, 0xcb, 0x94, 0x6e, 0xea,
	0x9f, 0x3c, 0x5b, 0x3f, 0x4d, 0xb8, 0x1e, 0x1d, 0x70, 0xd5, 0x41, 0xe7, 0xab, 0x82, 0xff, 0x8f,
	0x61, 0x4a, 0x93, 0xec, 0x36, 0x4c, 0x71, 0x22, 0x10, 0x23, 0x5c, 0x3b, 0x7f, 0x52, 0x77, 0x2a,
	0x4a, 0x74, 0xea, 0x00, 0xda, 0x99, 0xc8, 0xfc, 0x5b, 0x22, 0xd5, 0x72, 0x65, 0x80, 0x03, 0x25,
	0xf6, 0xaf, 0xf9, 0x4f, 0xfe, 0x9d, 0x7a, 0x2d, 0x79, 0x98, 0x67, 0x66, 0xe2, 0x93, 0x32, 0x2e,
	0x0f, 0xb1, 0xba, 0xe2, 0xbe, 0x7b, 0xaa, 0xc3, 0x33, 0x95, 0xea, 0xda, 0x0f, 0xac, 0xee, 0xf8,
	0x05, 0x98, 0xaa, 0x57, 0x59, 0x17, 0x5a, 0x17, 0x61, 0x72, 0x6b, 0xed, 0x31, 0x13, 0x8c, 0xa9,
	0x58, 0x59, 0xda, 0xf1, 0x6f, 0xf2, 0x3b, 0x8a, 0x8f, 0x93, 0x0d, 0xa0, 0xe7, 0x2d, 0x63, 0x9e,
	0xb8, 0x42, 0x64, 0xd6, 0x1e, 0xfb, 0x12, 0x1e, 0x9f, 0x47, 0x19, 0x4f, 0xe2, 0x24, 0x4c, 0xf9,
	0x24, 0x58, 0x84, 0x91, 0xa5, 0xb1, 0x03, 0xb0, 0xca, 0xcd, 0x53, 0xfa, 0xae, 0x5b, 0x3a, 0x03,
	0xe8, 0xa8, 0xb5, 0xc1, 0xfa, 0x60, 0xfe, 0x12, 0xa6, 0x61, 0x26, 0x12, 0xab, 0x75, 0xf2, 0xb7,
	0x09, 0x7d, 0x79, 0x7b, 0xf2, 0x31, 0x9c, 0x73, 0xf6, 0x3d, 0x74, 0x26, 0x41, 0x80, 0x9e, 0xda,
	0x9b, 0xcc, 0xf3, 0xe9, 0x3f, 0x1c, 0xd6, 0xd4, 0xa4, 0x3a, 0xc1, 0xd9, 0x63, 0x13, 0xe8, 0x5c,
	0xf0, 0x0c, 0x11, 0xb6, 0x6a, 0xff, 0xb0, 0xe4, 0x69, 0x86, 0x62, 0x35, 0x40, 0x9c, 0x81, 0x79,
	0xc1, 0xb3, 0xe9, 0xea, 0xf2, 0x8c, 0x3d, 0xaf, 0xc7, 0x38, 0x7b, 0x00, 0xca, 0x39, 0x00, 0xa1,
	0xfc, 0x4c, 0x43, 0xe5, 0xb3, 0xc9, 0xbc, 0x82, 0x3e, 0xc1, 0xa8, 0x57, 0xf7, 0xd9, 0x38, 0x13,
	0xe8, 0x12, 0x0e, 0xce, 0x91, 0xc3, 0x5a, 0x6d, 0xa7, 0xab, 0x06, 0x88, 0x0b, 0x00, 0x39, 0x7a,
	0xa7, 0x7e, 0xca, 0x6b, 0xa4, 0x29, 0x67, 0x73, 0x03, 0xd0, 0x25, 0xec, 0xcb, 0x73, 0xaa, 0xa8,
	0x7a, 0x28, 0x99, 0x6c, 0x2c, 0xab, 0xe7, 0xf2, 0x85, 0xf8, 0xc8, 0x1b, 0x1c, 0x3f, 0xac, 0x41,
	0xc1, 0x84, 0xb3, 0xc7, 0x4e, 0xc9, 0x6e, 0x7a, 0xb4, 0xcf, 0x6a, 0x89, 0x60, 0x6a, 0xf8, 0x7c,
	0x07, 0x0d, 0x4c, 0x92, 0xdb, 0x3d, 0xe9, 0xb6, 0x7f, 0xbd, 0x8b, 0x07, 0xa6, 0x9a, 0x60, 0x5e,
	0x29, 0x97, 0x7e, 0xe0, 0xbb, 0x54, 0x91, 0x9f, 0xd3, 0x26, 0x9c, 0x53, 0xe8, 0x49, 0x85, 0xd1,
	0xee, 0xfa, 0xa7, 0xe4, 0xcd, 0xbc, 0xe6, 0x0e, 0x96, 0x20, 0x34, 0xb6, 0xeb, 0xb5, 0xc1, 0xd4,
	0xfd, 0x30, 0xd3, 0xfd, 0x5f, 0xa1, 0xfc, 0x5f, 0xff, 0x6d, 0x87, 0xd6, 0xdf, 0xfe, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x3c, 0x6d, 0xcb, 0xaa, 0x25, 0x0c, 0x00, 0x00,
}
