// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/wechat.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WechatType int32

const (
	WechatType_Default WechatType = 0
	WechatType_OpenID  WechatType = 1
	WechatType_Union   WechatType = 2
)

var WechatType_name = map[int32]string{
	0: "Default",
	1: "OpenID",
	2: "Union",
}

var WechatType_value = map[string]int32{
	"Default": 0,
	"OpenID":  1,
	"Union":   2,
}

func (x WechatType) String() string {
	return proto.EnumName(WechatType_name, int32(x))
}

func (WechatType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24666104a66f189b, []int{0}
}

type WechatInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              uint64   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              uint64   `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Open                 string   `protobuf:"bytes,7,opt,name=open,proto3" json:"open,omitempty"`
	Union                string   `protobuf:"bytes,8,opt,name=union,proto3" json:"union,omitempty"`
	Portrait             string   `protobuf:"bytes,9,opt,name=portrait,proto3" json:"portrait,omitempty"`
	Name                 string   `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WechatInfo) Reset()         { *m = WechatInfo{} }
func (m *WechatInfo) String() string { return proto.CompactTextString(m) }
func (*WechatInfo) ProtoMessage()    {}
func (*WechatInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_24666104a66f189b, []int{0}
}

func (m *WechatInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WechatInfo.Unmarshal(m, b)
}
func (m *WechatInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WechatInfo.Marshal(b, m, deterministic)
}
func (m *WechatInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WechatInfo.Merge(m, src)
}
func (m *WechatInfo) XXX_Size() int {
	return xxx_messageInfo_WechatInfo.Size(m)
}
func (m *WechatInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WechatInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WechatInfo proto.InternalMessageInfo

func (m *WechatInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *WechatInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WechatInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *WechatInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *WechatInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *WechatInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *WechatInfo) GetOpen() string {
	if m != nil {
		return m.Open
	}
	return ""
}

func (m *WechatInfo) GetUnion() string {
	if m != nil {
		return m.Union
	}
	return ""
}

func (m *WechatInfo) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

func (m *WechatInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReqWechatBy struct {
	Uid                  string     `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type                 WechatType `protobuf:"varint,2,opt,name=type,proto3,enum=omo.msp.user.WechatType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReqWechatBy) Reset()         { *m = ReqWechatBy{} }
func (m *ReqWechatBy) String() string { return proto.CompactTextString(m) }
func (*ReqWechatBy) ProtoMessage()    {}
func (*ReqWechatBy) Descriptor() ([]byte, []int) {
	return fileDescriptor_24666104a66f189b, []int{1}
}

func (m *ReqWechatBy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqWechatBy.Unmarshal(m, b)
}
func (m *ReqWechatBy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqWechatBy.Marshal(b, m, deterministic)
}
func (m *ReqWechatBy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqWechatBy.Merge(m, src)
}
func (m *ReqWechatBy) XXX_Size() int {
	return xxx_messageInfo_ReqWechatBy.Size(m)
}
func (m *ReqWechatBy) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqWechatBy.DiscardUnknown(m)
}

var xxx_messageInfo_ReqWechatBy proto.InternalMessageInfo

func (m *ReqWechatBy) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqWechatBy) GetType() WechatType {
	if m != nil {
		return m.Type
	}
	return WechatType_Default
}

type ReqWechatAdd struct {
	Open                 string   `protobuf:"bytes,1,opt,name=open,proto3" json:"open,omitempty"`
	Union                string   `protobuf:"bytes,2,opt,name=union,proto3" json:"union,omitempty"`
	Portrait             string   `protobuf:"bytes,3,opt,name=portrait,proto3" json:"portrait,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqWechatAdd) Reset()         { *m = ReqWechatAdd{} }
func (m *ReqWechatAdd) String() string { return proto.CompactTextString(m) }
func (*ReqWechatAdd) ProtoMessage()    {}
func (*ReqWechatAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_24666104a66f189b, []int{2}
}

func (m *ReqWechatAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqWechatAdd.Unmarshal(m, b)
}
func (m *ReqWechatAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqWechatAdd.Marshal(b, m, deterministic)
}
func (m *ReqWechatAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqWechatAdd.Merge(m, src)
}
func (m *ReqWechatAdd) XXX_Size() int {
	return xxx_messageInfo_ReqWechatAdd.Size(m)
}
func (m *ReqWechatAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqWechatAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqWechatAdd proto.InternalMessageInfo

func (m *ReqWechatAdd) GetOpen() string {
	if m != nil {
		return m.Open
	}
	return ""
}

func (m *ReqWechatAdd) GetUnion() string {
	if m != nil {
		return m.Union
	}
	return ""
}

func (m *ReqWechatAdd) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

func (m *ReqWechatAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqWechatAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReqWechatUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Open                 string   `protobuf:"bytes,2,opt,name=open,proto3" json:"open,omitempty"`
	Union                string   `protobuf:"bytes,3,opt,name=union,proto3" json:"union,omitempty"`
	Portrait             string   `protobuf:"bytes,4,opt,name=portrait,proto3" json:"portrait,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqWechatUpdate) Reset()         { *m = ReqWechatUpdate{} }
func (m *ReqWechatUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqWechatUpdate) ProtoMessage()    {}
func (*ReqWechatUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_24666104a66f189b, []int{3}
}

func (m *ReqWechatUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqWechatUpdate.Unmarshal(m, b)
}
func (m *ReqWechatUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqWechatUpdate.Marshal(b, m, deterministic)
}
func (m *ReqWechatUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqWechatUpdate.Merge(m, src)
}
func (m *ReqWechatUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqWechatUpdate.Size(m)
}
func (m *ReqWechatUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqWechatUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqWechatUpdate proto.InternalMessageInfo

func (m *ReqWechatUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqWechatUpdate) GetOpen() string {
	if m != nil {
		return m.Open
	}
	return ""
}

func (m *ReqWechatUpdate) GetUnion() string {
	if m != nil {
		return m.Union
	}
	return ""
}

func (m *ReqWechatUpdate) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

func (m *ReqWechatUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqWechatUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReplyWechatInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *WechatInfo  `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyWechatInfo) Reset()         { *m = ReplyWechatInfo{} }
func (m *ReplyWechatInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyWechatInfo) ProtoMessage()    {}
func (*ReplyWechatInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_24666104a66f189b, []int{4}
}

func (m *ReplyWechatInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyWechatInfo.Unmarshal(m, b)
}
func (m *ReplyWechatInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyWechatInfo.Marshal(b, m, deterministic)
}
func (m *ReplyWechatInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyWechatInfo.Merge(m, src)
}
func (m *ReplyWechatInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyWechatInfo.Size(m)
}
func (m *ReplyWechatInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyWechatInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyWechatInfo proto.InternalMessageInfo

func (m *ReplyWechatInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyWechatInfo) GetInfo() *WechatInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterEnum("omo.msp.user.WechatType", WechatType_name, WechatType_value)
	proto.RegisterType((*WechatInfo)(nil), "omo.msp.user.WechatInfo")
	proto.RegisterType((*ReqWechatBy)(nil), "omo.msp.user.ReqWechatBy")
	proto.RegisterType((*ReqWechatAdd)(nil), "omo.msp.user.ReqWechatAdd")
	proto.RegisterType((*ReqWechatUpdate)(nil), "omo.msp.user.ReqWechatUpdate")
	proto.RegisterType((*ReplyWechatInfo)(nil), "omo.msp.user.ReplyWechatInfo")
}

func init() {
	proto.RegisterFile("proto/user/wechat.proto", fileDescriptor_24666104a66f189b)
}

var fileDescriptor_24666104a66f189b = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0xbb, 0xb9, 0x24, 0xd7, 0x9b, 0x3b, 0xeb, 0xb1, 0x08, 0x6e, 0x0f, 0x0a, 0xe5, 0x9e,
	0x8a, 0x48, 0xaa, 0xe7, 0x27, 0xe8, 0x71, 0x22, 0x05, 0xa5, 0x90, 0x5a, 0x04, 0xdf, 0xe2, 0xed,
	0x1e, 0x06, 0x9a, 0xdd, 0x75, 0xb3, 0x51, 0xf2, 0xee, 0x97, 0xf0, 0x2b, 0xfa, 0xe8, 0x27, 0x90,
	0x9d, 0x6d, 0x72, 0xb1, 0x26, 0xed, 0xdb, 0xce, 0xcc, 0x7f, 0xfe, 0xfc, 0x66, 0x26, 0x04, 0x9e,
	0x6b, 0xa3, 0xac, 0x3a, 0xaf, 0x4a, 0x61, 0xce, 0x7f, 0x88, 0xed, 0xd7, 0xcc, 0x26, 0x98, 0xa1,
	0x33, 0x55, 0xa8, 0xa4, 0x28, 0x75, 0xe2, 0x4a, 0x8b, 0xae, 0x6c, 0xab, 0x8a, 0x42, 0x49, 0x2f,
	0x5b, 0xfe, 0x21, 0x00, 0x9f, 0xb0, 0xef, 0x52, 0xee, 0x14, 0x9d, 0xc3, 0xa8, 0xca, 0x39, 0x23,
	0xa7, 0xe4, 0x6c, 0x92, 0xba, 0x27, 0x3d, 0x82, 0x20, 0xe7, 0x2c, 0x38, 0x25, 0x67, 0x61, 0x1a,
	0xe4, 0x9c, 0x32, 0x18, 0x6f, 0x8d, 0xc8, 0xac, 0xe0, 0x6c, 0x84, 0xc9, 0x26, 0x74, 0x95, 0x4a,
	0x73, 0xac, 0x84, 0xbe, 0x72, 0x17, 0xb6, 0x3d, 0xca, 0xb0, 0x08, 0x9d, 0x9b, 0x90, 0x2e, 0xe0,
	0x50, 0x69, 0x61, 0xb0, 0x14, 0x63, 0xa9, 0x8d, 0x29, 0x85, 0x50, 0x69, 0x21, 0xd9, 0x18, 0xf3,
	0xf8, 0xa6, 0xcf, 0x20, 0xaa, 0x64, 0xae, 0x24, 0x3b, 0xc4, 0xa4, 0x0f, 0x9c, 0x8b, 0x56, 0xc6,
	0x9a, 0x2c, 0xb7, 0x6c, 0xe2, 0x5d, 0x9a, 0xd8, 0xb9, 0xc8, 0xac, 0x10, 0x0c, 0xbc, 0x8b, 0x7b,
	0x2f, 0x3f, 0xc0, 0x34, 0x15, 0xdf, 0xfc, 0xd8, 0xeb, 0xba, 0x67, 0xe8, 0x97, 0x10, 0xda, 0x5a,
	0x0b, 0x1c, 0xfb, 0x68, 0xc5, 0x92, 0xee, 0x2e, 0x13, 0xdf, 0xf7, 0xb1, 0xd6, 0x22, 0x45, 0xd5,
	0xf2, 0x27, 0x81, 0x59, 0xeb, 0x77, 0xc1, 0x79, 0x4b, 0x4e, 0xfa, 0xc8, 0x83, 0x21, 0xf2, 0xd1,
	0x3d, 0xf2, 0xee, 0x6e, 0xc2, 0xff, 0x77, 0x83, 0x53, 0x45, 0x9d, 0xa9, 0x7e, 0x11, 0x78, 0xda,
	0x62, 0xdc, 0xe0, 0xea, 0x7b, 0x46, 0x6b, 0xd8, 0x82, 0x3e, 0xb6, 0xd1, 0x10, 0x5b, 0xf8, 0x00,
	0x5b, 0x34, 0xc0, 0x16, 0x77, 0xd8, 0x8c, 0x43, 0xd3, 0xb7, 0x75, 0xe7, 0x53, 0x7b, 0x0d, 0x71,
	0x69, 0x33, 0x5b, 0x95, 0x48, 0x37, 0x5d, 0x1d, 0xff, 0xbb, 0x65, 0x94, 0x5f, 0xa3, 0x20, 0xbd,
	0x13, 0xba, 0xb3, 0xe4, 0x72, 0xa7, 0x90, 0x7d, 0xda, 0x7f, 0x16, 0x67, 0x9d, 0xa2, 0xea, 0xc5,
	0xab, 0xe6, 0xcb, 0x76, 0xa7, 0xa2, 0x53, 0x18, 0x6f, 0xc4, 0x2e, 0xab, 0x6e, 0xed, 0xfc, 0x80,
	0x02, 0xc4, 0x57, 0x5a, 0xc8, 0xcb, 0xcd, 0x9c, 0xd0, 0x09, 0x44, 0x37, 0x6e, 0xde, 0x79, 0xb0,
	0xfa, 0x4d, 0xe0, 0x89, 0x6f, 0xb9, 0x16, 0xe6, 0x7b, 0xbe, 0x15, 0xf4, 0x2d, 0xc4, 0x17, 0x9c,
	0x5f, 0x49, 0x41, 0x17, 0xf7, 0xf1, 0xf6, 0xf7, 0x5e, 0x9c, 0xf4, 0xa0, 0xef, 0x71, 0x96, 0x07,
	0x74, 0x03, 0xf1, 0x3b, 0x61, 0x9d, 0xcd, 0xf1, 0x80, 0xcd, 0xba, 0x7e, 0xdc, 0xe5, 0x3d, 0x80,
	0x3f, 0xeb, 0x3a, 0x2b, 0x05, 0x3d, 0x19, 0x70, 0xf2, 0x92, 0x47, 0xdd, 0xd6, 0xb3, 0xcf, 0xb0,
	0xff, 0x29, 0x7c, 0x89, 0xf1, 0xfd, 0xe6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x36, 0x4d,
	0xba, 0x50, 0x04, 0x00, 0x00,
}
